### ISSUE TITLE
Bug in Zonemaster::Test::Syntax (syntax04, syntax07 and syntax08)

### ISSUE THREAD

**Issue by vlevigneron** [dotse/zonemaster#107]
With very broken testing zones zone02.zut-root.rd.nic.fr and zone01.zut-root.rd.nic.fr (look at SOA MNAME, MX AND NS list) I discovered that the '.' case was not properly handled... I'll fix it today and will add proper error messages for that new cases...

**Comment by pawal** [comment]
This issue was moved to dotse/zonemaster-engine#12
