### ISSUE TITLE
Complete installation instructions

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#137]
Update and/or create the instructions on installation for the engine, the CLI and the web interface in good time before the first release candidate.

**Comment by einar** [comment]
The backend documentation needs more work (but I think Sandoche is on that one). The frontend misses any and all information about databases so I'm currently guessing along as I install it.

If you cant install it from a CLEAN machine then the install document is not ready, people shouldnt have to guess what is meant. The Engine can be installed with cut and paste from the instruction (tested it several times on newly installed machines)... ;p

**Comment by einar** [comment]
...ignore mention of database, I now realize the frontend uses the backend API (wasnt that obvious). ;) Some information about this would be nice...

**Comment by jpierre03** [comment]
what about

**Comment by pawal** [comment]
@jpierre03 Sure, I like the idea. We have decided we won't do packaging, but I am not sure about examples such as this. It is certainly an idea to consider.

I just tried your image, and it seems to work ok so far. Not sure how to make it connect with IPv6 though.

**Comment by jpierre03** [comment]
@pawal IPv6 is an issue with docker by now (not as simple as IPv4).
For IPv4 it's an out-of-the-box sandbox  and to check with --no-ipv6 ;)

I'm trying to set up an IPv6 command line -> More info if it works.
