### ISSUE TITLE
History of previous tests should preload

### ISSUE THREAD

**Issue by einar** [dotse/zonemaster#209]
As it is now you have to complete a test to get history for a domain (unless it has been cached). If possible we should preload the history as soon as a user confirms a test (with all the links to previous runs) so he doesnt have to wait a full test cycle if he simply wants to see history.

Yes, there's a use case for this. I do it all the time when people ask me about results; I start a test on the same domain then just jump to their actual test in the list instead of completing my own (since few people remember to send a link). ;)

**Comment by pawal** [comment]
This issue was moved to dotse/zonemaster-gui#47
