### ISSUE TITLE
Results are not translated in the language chosen in the index

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster#220]
[Requirement] 
When a user has chosen a language the index, faq and results MUST be in
the chosen language UNLESS specific messages are missing where in such a case
the default language COULD be used for these, or all, messages.

Test: 
1. afnic.fr (Chosen lang "en")
2. Choose other language such as "fr" or "sw", the results are still in English

**Comment by pawal** [comment]
This issue was moved to dotse/zonemaster-gui#41
