### ISSUE TITLE
Future tests from the Requirements document

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#257]
There is a rest list from the Test Requirements document:

https://github.com/dotse/zonemaster/blob/master/docs/requirements/TestRequirements.md#future-tests

 * Case insensitivity in a name server, [RFC 4343](http://tools.ietf.org/html/rfc4343).
 * More tests of EDNS(0), [RFC 6891](http://tools.ietf.org/search/rfc6891).
 * AXFR is complex, perhaps do more inspection of data coming from AXFR,
   [RFC 5936](https://tools.ietf.org/html/rfc5936).
 * Check for algorithm completeness (DS->DNSKEY->RRSIG) as per section 2.2 of
   [RFC 4035](http://tools.ietf.org/html/rfc4035#section-2.2).
 * domain of the hostmaster email is not an openrelay
 * can deliver email to 'postmaster'
 * can deliver email to hostmaster
 * domain able to receive email (delivery using MX, A, AAAA)
 * test if mail delivery possible
 * ICMP answer
 * Test for referral to root (possible DDoS vector for authoritative name servers)
 * Check to see if removed authoritative name server is still authoritative (requires
   a new input parameter, "previous ns")
 * Test the preservation of qname case in DNS answers, RFC 1035 section 7.1. ("0x20" hack)

Add separate tickets for these at some point.

**Comment by pawal** [comment]
Is it time now to create in issue of each individual new test spec we want, or do we do this after our meeting discussing the roadmap?

**Comment by sandoche2k** [comment]
My view is - It is better to start now itself.

**Comment by pawal** [comment]
I have added these issues now.
