### ISSUE TITLE
asnlookup.zonemaster.net does not have working IPv6 glue

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#263]
<subject> causes --no-ipv4 to fail ASN lookups in that test case. This can be fixed in various ways:
- Fix rbldnsd to read correct AAAA glue
- Fix ASN lookup module in the engine
- Look for alternative server software

**Comment by matsduf** [comment]
Wait for solution.

**Comment by bortzmeyer** [comment]
You mean a [dnsdist](https://dnsdist.org/)?

**Comment by matsduf** [comment]
> You mean a [dnsdist](https://dnsdist.org/)?

Yes, of course. I mixed things up when editing. I have corrected above. Thank you, @bortzmeyer!

**Comment by matsduf** [comment]
@tgreenx, we solved this by not having any glue at all. The name servers are not in-bailiwick, which means that there is no need for the address records for the name servers to be in the zone.
