### ISSUE TITLE
Benchmark quality of tests with Zonecheck and DNSCheck

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#267]
We need to validate the quality of the tests and test specification, so we need more benchmarking with the tools that is the requirements for Zonemaster.

**Comment by sandoche2k** [comment]
@pawal assign to me and @einar

**Comment by pawal** [comment]
An issue can only be assigned one person. But @einar - feel free to participate anyway ;)

**Comment by einar** [comment]
Acknowledged! As usual Wednesdays and onwards I'm (most often) available for the record & to Sandoche! :)

**Comment by sandoche2k** [comment]
@einar - With other benchmarking metrics done, i think we now have to look to benchmark the test specifications. How do we do that :-)?

**Comment by sandoche2k** [comment]
I am closing this to create a new issue with with more specific wordings.
