### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#268]
From the release process section in the Technical Maintenance Plan:

In order to create a release after the decision to make a release has been made, there are a number of tasks that has to be done:

 * Update the documentation
 * Testing
 * Generate the release (tar.gz, check for completeness)
 * Announcements
 * The Release Process should be documented in a more exact routine document so that anybody in the team can create a release.

The Release Manager is responsible for the Release Process and the Release Management Process.

Once the announcements are made, it is common practice to also give a friendly notice to any package maintainers that wants to package the new version.

**Comment by sandoche2k** [comment]
@pawal - where are we :-)? Can we assign a milestone for this task?

**Comment by pawal** [comment]
Done.
