### ISSUE TITLE
Print dates in ISO 8601-format

### ISSUE THREAD

**Issue by joelpurra** [dotse/zonemaster#279]
Current date format in the domain result history: `11.12.2014 16:17 `. To me this is "unparseable" as it introduces uncertainty (is the month 11 or 12?) for international usage. Try using the [ISO 8601 standard](https://en.wikipedia.org/wiki/ISO_8601) instead.

    Date and time (current at page generation) expressed according to ISO 8601:
    Date:							2014-12-11
    Combined date and time in UTC:	2014-12-11T05:45:46+00:00
    								2014-12-11T05:45:46Z
    Week:							2014-W50
    Date with week number:			2014-W50-4
    Ordinal date:					2014-345

**Comment by pawal** [comment]
This issue was moved to dotse/zonemaster-gui#36
