### ISSUE TITLE
Link to /nojs doesn't work when javascript is enabled

### ISSUE THREAD

**Issue by joelpurra** [dotse/zonemaster#280]
The the non-javascript version is great - love it! Unfortunately the link in the main interface doesn't work when javascript is enabled.

1. Use a browser with javascript enabled.
1. Go to http://zonemaster.net/
1. Click the link to the "Non-Javascript Interface".
1. The URL in the browser window's address bar changes, but nothing actually happens.

Expected to go to http://zonemaster.net/nojs as it looks when entering the URL manually.

**Comment by pawal** [comment]
This issue was moved to dotse/zonemaster-gui#35
