### ISSUE TITLE
Incorrect test for "same AS"

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#291]
http://zonemaster.net/test/1268 (.pizza)

Zonemaster says " All nameservers IPv4 addresses are in the same AS (18210 58620). " It is funny to claim there is one AS then to display two AS numbers :-)

Actually, there are indeed two AS. The bug may have been triggered by the fact that, in IPv6, there is only one.

**Comment by vincib** [comment]
It seems that this is still the case (or similar) with IPv6 AS detection : https://www.zonemaster.fr/test/9eac7a64004bfb8c It pretends I have only 1 AS for IPv6, although the secondary NS is in a different AS. It can't find the AS of the secondary, which is 2600:3c01::f03c:91ff:fedf:7526 (OriginAS:       AS3595, AS36351, AS6939, AS15830, AS8001, AS2516)

**Comment by pawal** [comment]
This is the debug output from Zonemaster:

```
  18.70 DEBUG     [ASN:RAW] 173.230.154.187;6939 | 173.230.144.0/20 | US | arin | 2010-03-15
  18.70 DEBUG     [ASN:ANNOUNCE_BY] 173.230.154.187;6939
  18.70 DEBUG     [ASN:ANNOUNCE_IN] 173.230.154.187;173.230.144.0/20
  18.70 DEBUG     [ASN:RAW] 91.194.60.99;39389 | 91.194.60.0/23 | FR | ripencc | 2007-06-04
  18.71 DEBUG     [ASN:ANNOUNCE_BY] 91.194.60.99;39389
  18.71 DEBUG     [ASN:ANNOUNCE_IN] 91.194.60.99;91.194.60.0/23
  19.06 DEBUG     [ASN:RAW] 2001:67c:288::99;39389 | 2001:67c:288::/48 | FR | ripencc | 2010-07-14
  19.06 DEBUG     [ASN:ANNOUNCE_BY] 2001:67c:288::99;39389
  19.06 DEBUG     [ASN:ANNOUNCE_IN] 2001:67c:288::99;2001:67c:288::/48
```

The Linode IPv6 ASN does not show up.
