### ISSUE TITLE
Suboptimal messages when the domain is not a zone

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#294]
When testing a domain which is not a zone (something which is common under .arpa), the messages are very misleading:

http://zonemaster.net/test/1334

"Not enough data about gouv.fr was found to be able to run tests."
 "Nameservers for "fr" provided no NS records for tested zone. RCODE given was NOERROR."

I suggest a better wording:

"The domain gouv.fr exists but is apparently not a zone. Zonemaster can only analyze DNS zones. May be try the parent zone, fr?"

**Comment by pawal** [comment]
This is closed with commit https://github.com/dotse/zonemaster-engine/commit/c4560bc25acbf4fe154d5bd5905d93f25a396764.

**Comment by bortzmeyer** [comment]
I strongly disagree with the new error message. gouv.fr or www.elysee.fr *are* domains. The new message is wrong and should be "is not a zone".
