### ISSUE TITLE
Classless in-addr.arpa

### ISSUE THREAD

**Issue by tobbe-eklov** [dotse/zonemaster#301]
Hi, sometime's it fails with in-addr.arpa

Ex.

zonemaster-cli --level INFO --raw torsas.se

gives:

 3.53 WARNING   ADDRESS:NAMESERVER_IP_WITHOUT_REVERSE address=62.20.107.197, ns=dns.torsas.se

But there is a classless in-addr.arpa

host 62.20.107.197
197.107.20.62.in-addr.arpa is an alias for 197.192-27.107.20.62.in-addr.arpa.
197.192-27.107.20.62.in-addr.arpa domain name pointer ns.torsas.se.
197.192-27.107.20.62.in-addr.arpa domain name pointer dns.torsas.se.

/Tobbe

**Comment by pawal** [comment]
This issue was moved to dotse/zonemaster-engine#14
