### ISSUE TITLE
Case insensitivity in a name server

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#304]
From Future tests in the Test Requirements:

Case insensitivity in a name server, [RFC 4343](http://tools.ietf.org/html/rfc4343).

**Comment by sandoche2k** [comment]
@pawal - move it to 2015.3

**Comment by sandoche2k** [comment]
@pawal isn't this same as #372

**Comment by pawal** [comment]
No.

These are two examples of two different behaviours.

1) CaSe InseNsiTiVity is that you get replies with an answer correctly, regardless of the case in the query.

2) Case preservation is where the answer contains the same CaSe InseNsiTiVity string as in the query.

**Comment by sandoche2k** [comment]
Thanks for the enlightenment :-)

I will update the test spec.

**Comment by sandoche2k** [comment]
@vlevigneron test spec written -nameserver09.md

**Comment by sandoche2k** [comment]
@vlevigneron Similarly can you verify and close this issue also.

**Comment by sandoche2k** [comment]
@vlevigneron close?

**Comment by vlevigneron** [comment]
nameserver09 has not been yet implemented.

2015-06-30 16:13 GMT+02:00 sandoche2k <notifications@github.com>:

**Comment by sandoche2k** [comment]
@vlevigneron - Do you require any i/ps for implementing this issue?
