### ISSUE TITLE
More tests of EDNS(0)

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#305]
From Future tests in the Test Requirements:

More tests of EDNS(0), [RFC 6891](http://tools.ietf.org/search/rfc6891).

**Comment by pawal** [comment]
See also RFC 4035 section 4.1: https://tools.ietf.org/html/rfc4035#section-4.1

**Comment by pawal** [comment]
Task:

Find these log messages in the current test cases:
    NAMESERVER:EDNS0_BAD_ANSWER
    NAMESERVER:EDNS0_BAD_QUERY
    NAMESERVER:EDNS0_SUPPORT

Add text to these test cases in the specifications to be more explicit about EDNS.

**Comment by sandoche2k** [comment]
@pawal - move it to 2015.3

**Comment by pawal** [comment]
Why would we want to postpone this even longer?

**Comment by sandoche2k** [comment]
2015.2 is to finish all the basic issues of GUI, backend, documentation for
them, monitoring and statistics.

I have pushed all other high priority issues to 2015.3.

**Comment by sandoche2k** [comment]
@pawal Are we still concerned about this issue?

**Comment by pawal** [comment]
Yes, read through the comments on this issue. More logging and modification of test cases.

**Comment by sandoche2k** [comment]
@vlevigneron please have a look at the comments by Patrik W.

**Comment by bortzmeyer** [comment]
As of today, Zonemaster seems to *not* test EDNS support which, in 2015, is certainly a problem. For instance, vache.fr 's name servers reply FORMERR but it is not displayed in https://zonemaster.net/test/35480 It certainly deserves a warning.

**Comment by vlevigneron** [comment]
It is displayed (look under nameserver category), but it is not considered (with current policy) as a warning. Perhaps policy could be upgraded in that way.

**Comment by sandoche2k** [comment]
@VLE close it after upgrade the EDNS policy to “warning” in the engine
