### ISSUE TITLE
ICMP answer

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#310]
From Future tests in the Test Requirements:

 * ICMP answer

**Comment by sandoche2k** [comment]
Earlier discussion on this test had suggestions that this test should be
categorised "warning"

**Comment by cdybedahl** [comment]
This test comes from Zonecheck, so maybe someone from AFNIC can clarify what kind of problem it is intended to detect?

**Comment by pawal** [comment]
Also, is there any good reference for as to why ICMP is a problem for DNS?
