### ISSUE TITLE
Test for referral to root

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#311]
From Future tests in the Test Requirements:

 * Test for referral to root (possible DDoS vector for authoritative name servers)

**Comment by pawal** [comment]
If suitable for Zonemaster, this should fit in the Nameserver test category.

**Comment by sandoche2k** [comment]
@pawal move it to 2015.3

**Comment by sandoche2k** [comment]
@vlevigneron test specification updated. Please verify.

**Comment by vlevigneron** [comment]
Code has been done but:

1/ Check new messages in policy file 
2/ Is there an example with an upward referral ? (I'll do unit tests
   afterwards)
3/ No translation of messages until we agree on english version.



le 05 juin, sandoche2k a ?crit :
> @vlevigneron test specification updated. Please verify.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster/issues/311#issuecomment-109205875

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr

**Comment by sandoche2k** [comment]
@vlevigneron re-opening this issue based on error report from @mtoma

**Comment by vlevigneron** [comment]
Why ? I guess it has been fixed. Just waiting for the "pull request" to
be merged...

le 15 juin, sandoche2k a ?crit :
> @vlevigneron re-opening this issue based on error report from @mtoma 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster/issues/311#issuecomment-112310015

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr
