### ISSUE TITLE
Remove the dependency on ldns

### ISSUE THREAD

**Issue by cdybedahl** [dotse/zonemaster#315]
As a diagnostic tool, it is important for Zonemaster to have good control over the queries it sends and what happens to packets it receives. This is the reason we abandoned the `Net::DNS` module, and instead wrote our own `Net::LDNS`. This helped a lot, but there is still a dependency on code maintained outside our project (NLnet Labs' `ldns`). While it does overall work well, experience has shown that there are drawbacks. When bugs in `ldns` impact the quality of our tests, we are at the mercy of their release cycle to get them fixed. We also have no control over which version of the library is installed on a particular user's machine, or with what options it was installed. This particularly impacts newer additions to the DNS ecosystem, like IDN names or signed zones using GOST or ECDSA algorithms. The inability to deal with such things should be detected at installation time, not at the time the test is running (if nothing else so because the tests for it makes the test code more complex and thus harder to verify as correct).

The obvious way to fix this is to push our "bottom of control" even further down. Since we only use a subset of the functionality in `ldns` (we don't sign zones, for example), it's reasonable to extract the code we do use and put it directly into the C part of the `Net::LDNS` module. This would still leave us dependent on `OpenSSL` for implementations of cryptographic algorithms, but that is in much more widespread use than `ldns` (and thus more thoroughly tested), and we can complain at compilation about missing algorithms to a greater extent.

Importing the `ldns` code would also enable us to produce much better diagnostics of malformed DNS packets (which are currently discarded before our code ever see them) and broken implementations of EDNS0 (currently we cannot see raw OPT RRs), by doing modifications that would be of no (or even negative) use for ordinary `ldns` users.

**Comment by pawal** [comment]
This issue was moved to dotse/zonemaster-engine#26
