### ISSUE TITLE
Able to conduct tests for a batch of domains

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#316]
This issue was also documented in the [WishList for Version 2.0](https://github.com/dotse/zonemaster/blob/master/docs/requirements/WishList.md).

We have discussed batch testing in length. It still is a good idea, but maybe hard to make general enough for the open source project.

**Comment by mtoma** [comment]
There is already a "close to working" API for batch testing in the Backend.
I'm planning to use it to run a Zonecheck/Zonemaster comparison.

----- Original Message -----

**Comment by pawal** [comment]
How many threads can the backend run in parallel? Let me know when you have any performance figures.

**Comment by mtoma** [comment]
As many as you want.
It is as configurable as the frontend specific part of the backend.
It depends only on the material resources you have.
It process is simple:
1. Create your batch job defining the test perimeter.
2. Run a job executing script filling all available batch testing slots (this is why the process priorities are for in the runner scripts).
3. Wait for available slots and fill them until all tests are finished.
4. Close the batch job.

----- Original Message -----

**Comment by sandoche2k** [comment]
Can it be done via CLI or Interface web ?

**Comment by pawal** [comment]
Next step: Collect requirements on such a tool. And look into using the Backend API.

**Comment by sandoche2k** [comment]
@pawal Batch testing is possible via the backend
