### ISSUE TITLE
Alert if the domain does not use DNSSEC

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#318]
This issue was also documented in the [WishList for Version 2.0](https://github.com/dotse/zonemaster/blob/master/docs/requirements/WishList.md).

Alert if the domain does not use DNSSEC. Is this relevant?

**Comment by sandoche2k** [comment]
This was an input from Kim Minh Kaplan.

The idea is to inform the clients about good practice. We can discuss
whether we want to do DNS evangelism or not during F2F :-)

**Comment by pawal** [comment]
Low message level, NOTICE?

**Comment by pawal** [comment]
This issue was moved to dotse/zonemaster-engine#25
