### ISSUE TITLE
Parallel tests

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#322]
This issue was also documented in the [WishList for Version 2.0](https://github.com/dotse/zonemaster/blob/master/docs/requirements/WishList.md).

In order to increase the performance of Zonemaster, we talked about running tests in parallell rather than in sequence.

**Comment by cdybedahl** [comment]
If we rewrite the whole thing in Erlang this would just fall out naturally :-)

**Comment by pawal** [comment]
This issue was moved to dotse/zonemaster-engine#23
