### ISSUE TITLE
IANA test profile

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#324]
Add a test profile for matching the tests that are root delegation specific as required by IANA:

https://www.iana.org/help/nameserver-requirements

(And make sure that the requirements matches our test cases.)

**Comment by sandoche2k** [comment]
@pawal - move it to 2015.3

**Comment by sandoche2k** [comment]
@pawal create test profile example

**Comment by sandoche2k** [comment]
@pawal - please update the status for this issue.

**Comment by pawal** [comment]
@sandoche2k where did you put the profile, and will this be the correct place for it?

**Comment by sandoche2k** [comment]
Link :
https://github.com/dotse/zonemaster-engine/compare/master...sandoche2k:add-iana-profile?expand=1

I think ... it should be at the repository Zonemaster.

But currently, the profile file is here :
https://github.com/dotse/zonemaster-engine/tree/master/share

**Comment by sandoche2k** [comment]
@pawal - Can you have a look?

**Comment by mtoma** [comment]
The backend expects to find a iana.josn file.

**Comment by pawal** [comment]
Sandoche, you should not have the level ERROR on the SYSTEM, this will flow the output with debug info. Have you tried this?

**Comment by sandoche2k** [comment]
Hi Patrik,

   I will work on it today or tomorrow.
