### ISSUE TITLE
Spurious "Delegation from parent to child is not properly signed (no_dnskey)"

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#326]
```
% zonemaster-cli fr         
Seconds Level     Message
======= ========= =======
   8.62 ERROR     Delegation from parent to child is not properly signed (no_dnskey).
```

I do not see where the problem comes from. Most other TLD have no issues, even TLD of the same operator such as pm or yt. But wf exhibits the same error.

**Comment by vlevigneron** [comment]
Just look at zonemaster-cli results. No idea yet where it comes from but it now works for .fr, and the same strange behaviour occurs with .pm. Will work on it soon.

**Comment by pawal** [comment]
This is probably the same as https://github.com/dotse/zonemaster-engine/issues/10.

**Comment by vlevigneron** [comment]
It's linked, but not sure this is the same. In this case, I suspect we display messages during domain analysis, but in this case, final result can be different from intermediate results...

**Comment by vlevigneron** [comment]
Sorry Calle, just read the code and see your comment... :-)

**Comment by pawal** [comment]
This issue was moved to dotse/zonemaster-engine#22
