### ISSUE TITLE
Implement continuous integration for all modules

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#329]
Assign issues to the different modules, cli, engine, backend and gui.

**Comment by sandoche2k** [comment]
@pawal - move it to 2015.4

**Comment by sandoche2k** [comment]
@pawal we do have travis for all modules. Can this be closed?

**Comment by mtoma** [comment]
The idea here was to trigger the travis tests for all 3 components whit each commit of any of the 3 components. (to avoid having ARAU() strings in the test results after the engine was modified without checking impacts on the GUI)
Is this the case?

**Comment by pawal** [comment]
> On 19 Nov 2015, at 10:51, mtoma <notifications@github.com> wrote:
> 
> The idea here was to trigger the travis tests for all 3 components whit each commit of any of the 3 components. (to avoid having ARAU() strings in the test results after the engine was modified without checking impacts on the GUI)
> Is this the case?

When testing the GUI with Travis you must of course install all three modules, and do the proper tests for the GUI. If something changes in the Engine or the Backend and you do not detect it in your tests, your tests do not cover all your code paths.

**Comment by mtoma** [comment]
How do detect a regreession with a new release of the engine if the GUI travis test is not executed with a commit of the engine?

**Comment by pawal** [comment]
By making proper "make test" on the GUI when preparing a release?

**Comment by mtoma** [comment]
Yes, this will be detected at the time of release of GUI with some modification of the GUI which will trigger the travis test.
What about a release (very often the case) where the engine is the only released component?
(This is exactly what happened with the ARRAY strings appearing in the web interface).

Wasn't the engine regression test supposed to detect that one of its commit was going to break something in the GUI (by triggering the Travis test of the GUI)?

Am I supposed to follow all the engine commits myself and trigger the GUI Travis tests manually with each commit of the engine?

**Comment by pawal** [comment]
This is why we have distribution releases.

The obvious resolution to this is to release all components often, in coordination. I would personally like to see this.

As for your last question, we are preparing for a release for a distribution with all components. But this is not very imminent as of today. In the meantime, do not run components outside of a distribution release.

**Comment by mtoma** [comment]
Yes, I agree that distribution releases should allow to release all components after some basic (at least travis) tests.
But experience shows that to respond to users creating issues for already solved problems I'm asked to release the engine much more often than the official distribution cycle of all components.

What kind of problem do you see with any of the 3 components triggering the travis tests of all 3 of them for any pull request?

**Comment by patrikhson** [comment]
Hi,
I know you were looking for this, I found this stuff for you, take a look at <http://thehahintu.wingsandravioli.com/xybspqb>

All the best, paf@frobbit.se
