### ISSUE TITLE
Net::LDNS build fails on Ubuntu 12.04

### ISSUE THREAD

**Issue by sylvainfaivre** [dotse/zonemaster#333]
Note : this is off topic since this is about building the dependencies, and the installation instructions are for Ubuntu 14.04, while I am using Ubuntu 12.04.

*Feel free to close this report if you want*

On Ubuntu 12.04, the command :
sudo perl -MCPAN -e 'install Net::LDNS'
fails with :

"/usr/bin/perl" "-Iinc" "/usr/local/share/perl/5.14.2/ExtUtils/xsubpp"  -typemap "/usr/share/perl/5.14/ExtUtils/typemap"  src/LDNS.xs > src/LDNS.xsc && mv src/LDNS.xsc src/LDNS.c
cc -c  "-I." "-I." -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"0.70\" -DXS_VERSION=\"0.70\" -o src/LDNS.o -fPIC "-I/usr/lib/perl/5.14/CORE"  -DUSE_PPPORT src/LDNS.c
src/LDNS.xs: In function ‘XS_Net__LDNS__RR__DNSKEY_ds’:
src/LDNS.xs:1793:21: error: ‘LDNS_SHA384’ undeclared (first use in this function)
src/LDNS.xs:1793:21: note: each undeclared identifier is reported only once for each function it appears in
make: *** [src/LDNS.o] Error 1
  CDYBED/Net-LDNS-0.70.tar.gz
  /usr/bin/make -- NOT OK
'YAML' not installed, will not store persistent state
Running make test
  Can't test without successful make
Running make install
  Make had returned bad status, install seems impossible

**Comment by cdybedahl** [comment]
That error means your ldns library is too old. Specifically, older than version 1.6.13, which was released in May 2012. I know it's a bother, but those new algorithms are being used for DNSSEC today, and we need to have them.

**Comment by sylvainfaivre** [comment]
Thank you for your help.

As a note to anyone having the same problem, perl module Net::LDNS and zonemaster can be built on Ubuntu 12.04 Precise after installing libldns1_1.6.17-1_amd64.deb and libldns-dev_1.6.17-1_amd64.deb from Ubuntu 14.04 Trusty
