### ISSUE TITLE
Wrong french translation

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#334]
"Les serveurs de noms de la zone parente retournent suffisamment de serveurs autoritaires"

Authoritative means "faisant autorité", "Autoritaire" is "authoritarian".

**Comment by vlevigneron** [comment]
Fixed in commit e4e0e070222f9d15b5db82c3b43f7a1379248a98

**Comment by pawal** [comment]
Vincent, please refer to the issue when commiting the fix. You can use the issue number, the dotse/repo#issue-number or full link.
https://help.github.com/articles/closing-issues-via-commit-messages/
