### ISSUE TITLE
Net::LDNS install fails (via CPAN and manual install) - RHEL6

### ISSUE THREAD

**Issue by billyglynn** [dotse/zonemaster#336]
[root@zm Net-LDNS-0.70]# perl Makefile.PL
Writing ppport.h
Can't link/include C library 'ldns/ldns.h', 'ldns', aborting.

[root@zm Net-LDNS-0.70]# perl -MCPAN -e 'install Net::LDNS'
CPAN: Storable loaded ok (v2.20)
Going to read '/root/.cpan/Metadata'
  Database was generated on Thu, 05 Feb 2015 12:29:02 GMT
Running install for module 'Net::LDNS'
CPAN: YAML loaded ok (v0.70)
Running make for C/CD/CDYBED/Net-LDNS-0.70.tar.gz
CPAN: Digest::SHA loaded ok (v5.47)
CPAN: Compress::Zlib loaded ok (v2.021)
Checksum for /root/.cpan/sources/authors/id/C/CD/CDYBED/Net-LDNS-0.70.tar.gz ok
Net-LDNS-0.70/
Net-LDNS-0.70/inc/
Net-LDNS-0.70/lib/
Net-LDNS-0.70/LICENSE
Net-LDNS-0.70/Makefile.PL
Net-LDNS-0.70/MANIFEST
Net-LDNS-0.70/META.yml
Net-LDNS-0.70/ppport.h
Net-LDNS-0.70/README.md
Net-LDNS-0.70/src/
Net-LDNS-0.70/t/
Net-LDNS-0.70/t/axfr.t
Net-LDNS-0.70/t/dnssec.t
Net-LDNS-0.70/t/netldns.t
Net-LDNS-0.70/t/resolver.t
Net-LDNS-0.70/t/rr.t
Net-LDNS-0.70/t/rrlist.t
Net-LDNS-0.70/t/serialize.t
Net-LDNS-0.70/t/utils.t
Net-LDNS-0.70/src/LDNS.xs
Net-LDNS-0.70/src/typemap
Net-LDNS-0.70/lib/Net/
Net-LDNS-0.70/lib/Net/LDNS/
Net-LDNS-0.70/lib/Net/LDNS.pm
Net-LDNS-0.70/lib/Net/LDNS/Packet.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/
Net-LDNS-0.70/lib/Net/LDNS/RR.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/A.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/A6.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/AAAA.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/AFSDB.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/APL.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/ATMA.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/CAA.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/CDS.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/CERT.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/CNAME.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/DHCID.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/DLV.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/DNAME.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/DNSKEY.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/DS.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/EID.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/EUI48.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/EUI64.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/GID.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/GPOS.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/HINFO.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/HIP.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/IPSECKEY.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/ISDN.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/KEY.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/KX.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/L32.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/L64.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/LOC.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/LP.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/MAILA.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/MAILB.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/MB.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/MD.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/MF.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/MG.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/MINFO.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/MR.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/MX.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/NAPTR.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/NID.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/NIMLOC.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/NINFO.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/NS.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/NSAP.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/NSEC.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/NSEC3.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/NSEC3PARAM.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/NULL.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/NXT.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/PTR.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/PX.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/RKEY.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/RP.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/RRSIG.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/RT.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/SINK.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/SOA.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/SPF.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/SRV.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/SSHFP.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/TA.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/TALINK.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/TKEY.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/TLSA.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/TXT.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/TYPE.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/UID.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/UINFO.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/UNSPEC.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/URI.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/WKS.pm
Net-LDNS-0.70/lib/Net/LDNS/RR/X25.pm
Net-LDNS-0.70/inc/Module/
Net-LDNS-0.70/inc/Module/Install/
Net-LDNS-0.70/inc/Module/Install.pm
Net-LDNS-0.70/inc/Module/Install/Base.pm
Net-LDNS-0.70/inc/Module/Install/Can.pm
Net-LDNS-0.70/inc/Module/Install/Fetch.pm
Net-LDNS-0.70/inc/Module/Install/Makefile.pm
Net-LDNS-0.70/inc/Module/Install/Metadata.pm
Net-LDNS-0.70/inc/Module/Install/Win32.pm
Net-LDNS-0.70/inc/Module/Install/WriteAll.pm
Net-LDNS-0.70/inc/Module/Install/XSUtil.pm
CPAN: File::Temp loaded ok (v0.22)

  CPAN.pm: Going to build C/CD/CDYBED/Net-LDNS-0.70.tar.gz

Writing ppport.h
Can't link/include C library 'ldns/ldns.h', 'ldns', aborting.
No 'Makefile' created  CDYBED/Net-LDNS-0.70.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- NOT OK
Running make test
  Make had some problems, won't test
Running make install
  Make had some problems, won't install

**Comment by cdybedahl** [comment]
Looks like you don't have the ldns C library installed. Since this Perl module is only an interface to that, that's a pretty critical problem.

**Comment by billyglynn** [comment]
# rpm -qa | grep ldns
ldns-1.6.17-1.el6.x86_64
ldns-devel-1.6.17-1.el6.x86_64
ldns-python-1.6.17-1.el6.x86_64


---
Billy

**Comment by cdybedahl** [comment]
All right. So where does Redhat hide the header files, so that the C compiler can't find them (or the libraries so the linker can't find those)? Is there a web page somewhere that describes any special hoops needed to compile on Redhat?

**Comment by billyglynn** [comment]
# ls -l /usr/include/ldns/
total 408
-rw-r--r--. 1 root root 16649 Sep 30 20:23 buffer.h
-rw-r--r--. 1 root root  2146 Sep 30 20:23 common.h
-rw-r--r--. 1 root root  9102 Sep 30 20:23 dane.h
-rw-r--r--. 1 root root  6385 Sep 30 20:23 dname.h
-rw-r--r--. 1 root root 17124 Sep 30 20:23 dnssec.h
-rw-r--r--. 1 root root 14432 Sep 30 20:23 dnssec_sign.h
-rw-r--r--. 1 root root 30673 Sep 30 20:23 dnssec_verify.h
-rw-r--r--. 1 root root 14701 Sep 30 20:23 dnssec_zone.h
-rw-r--r--. 1 root root  2984 Sep 30 20:23 duration.h
-rw-r--r--. 1 root root  4099 Sep 30 20:23 error.h
-rw-r--r--. 1 root root  3361 Sep 30 20:23 higher.h
-rw-r--r--. 1 root root 31516 Sep 30 20:23 host2str.h
-rw-r--r--. 1 root root  5122 Sep 30 20:23 host2wire.h
-rw-r--r--. 1 root root 17268 Sep 30 20:23 keys.h
-rw-r--r--. 1 root root  4642 Sep 30 20:23 ldns.h
-rw-r--r--. 1 root root  7113 Sep 30 20:23 net.h
-rw-r--r--. 1 root root 25637 Sep 30 20:23 packet.h
-rw-r--r--. 1 root root  5621 Sep 30 20:23 parse.h
-rw-r--r--. 1 root root  6263 Sep 30 20:23 radix.h
-rw-r--r--. 1 root root  7489 Sep 30 20:23 rbtree.h
-rw-r--r--. 1 root root 11969 Sep 30 20:23 rdata.h
-rw-r--r--. 1 root root 23930 Sep 30 20:23 resolver.h
-rw-r--r--. 1 root root 12145 Sep 30 20:23 rr_functions.h
-rw-r--r--. 1 root root 27455 Sep 30 20:23 rr.h
-rw-r--r--. 1 root root  1165 Sep 30 20:23 sha1.h
-rw-r--r--. 1 root root  5514 Sep 30 20:23 sha2.h
-rw-r--r--. 1 root root  8520 Sep 30 20:23 str2host.h
-rw-r--r--. 1 root root  3796 Sep 30 20:23 tsig.h
-rw-r--r--. 1 root root  2725 Sep 30 20:23 update.h
-rw-r--r--. 1 root root 10601 Sep 30 20:23 util.h
-rw-r--r--. 1 root root  7261 Sep 30 20:23 wire2host.h
-rw-r--r--. 1 root root  4645 Sep 30 20:23 zone.h


https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Developer_Guide/compilers.html


---
Billy

**Comment by mtoma** [comment]
On a freshly installed ldns environments I usually need to execute "ldconfig" manually as it seems the "make install" of ldns is not doing it.
Other than this the installation worked for me on a RHEL 6.5

**Comment by billyglynn** [comment]
I tried that, with no success. I'll discard the VM and get a fresh one and
let you know. Thanks for your help.


---
Billy

**Comment by billyglynn** [comment]
i have it installed now. it needed openssl-devel

thanks


---
Billy

**Comment by cdybedahl** [comment]
That probably means that the ldns-devel package is missing that one as a requirement, because Net::LDNS itself only relies on OpenSSL by way of the ldns code. It does make sense that the ldns header files need the OpenSSL header files, but that means that the ldns-devel package is broken for everyone, not just for Net::LDNS. Do you want to have a look at that and possibly report the problem to the right place? I'll do it if not, but I can't say how long it'll be before I get the time to.

**Comment by billyglynn** [comment]
I've reported that on RedHat now. Cheers


---
Billy

**Comment by cdybedahl** [comment]
Thanks!
