### ISSUE TITLE
SOA MNAME does not respect --no-ipv6

### ISSUE THREAD

**Issue by einar** [dotse/zonemaster#339]
When testing a domain with IPv6 disabled you still get an error about SOA MNAME unreachable:
    22.42 NOTICE    SOA 'mname' nameserver ns.nic.se/2a00:801:f0:53::53 does not respond.

The domain "trasigdnssec.se" has ns.nic.se as MNAME which has both A and AAAA and the test ignores --no-ipv6 and gives a false positive (ns.nic.se IS reachable, over ipv4).

(ps. This could be a duplicate as I could've sworn I reported this a few months back... oh well. ;p ds.)

**Comment by pawal** [comment]
I see the same behaviour.
