### ISSUE TITLE
Improvements on structured JSON output

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#340]
I have been looking into analyzing results from many domains using the JSON output on file. The JSON data is not really structured in a convenient way to quickly fetch data from the structure.

Example of how it is now:

```
   {
      "timestamp" : 8.68917012214661,
      "module" : "ADDRESS",
      "level" : "NOTICE",
      "args" : {
         "address" : "192.36.133.107",
         "ns" : "b.ns.se",
         "names" : "se-dns.gbg.netnod.se."
      },
      "tag" : "NAMESERVER_IP_PTR_MISMATCH"
   },
   {
      "level" : "DEBUG",
      "module" : "DNSSEC",
      "timestamp" : 12.0075740814209,
      "tag" : "EXTRA_PROCESSING_OK",
      "args" : {
         "keys" : 3,
         "sigs" : 1,
         "server" : "192.36.133.107"
      }
   },
```

To quickly fetch the results of EXTRA_PROCESSING_OK you have to look into each result object and extract the tag value and its level.

I was thinking of perhaps make this easier by restructuring the data to something that could be used by JSONPath, and making it easier to extract each individual result of a test. Some of those tests are resulting in arrays, which makes it a little bit more complicated, but by restructuring the data to just something like this increases its usefulness.

Example:
```
"modules: ": [
  "ADDRESS": [
    "tags": [
      "NAMESERVER_IP_PTR_MISMATCH": [
           {
             "timestamp" : 8.68917012214661,
             "module" : "ADDRESS",
             "level" : "NOTICE",
             "args" : {
                "address" : "192.36.133.107",
                "ns" : "b.ns.se",
                "names" : "se-dns.gbg.netnod.se."
            }
         }
      ]
    ]
  ],
  "DNSSEC": [
    "tags": [
      "EXTRA_PROCESSING_OK": [
          "level" : "DEBUG",
          "module" : "DNSSEC",
          "timestamp" : 12.0075740814209,
          "tag" : "EXTRA_PROCESSING_OK",
          "args" : {
             "keys" : 3,
             "sigs" : 1,
             "server" : "192.36.133.107"
          }
      ]
    ]
  ]
]

and so on. Much more JSONPath friendly.

However, this will impact current users of the JSON data - so we need to give this some thought.

It could be that we will provide a new function for transforming the data for this.

**Comment by cdybedahl** [comment]
Can we really be sure that one JSON representation is universally more useful than another? Perhaps we should just take the JSON export functionality out of the engine and leave it up to the various tools to do whatever it is they need.

Or we could put in support for XSLT 3.0 and let users of the engine specify stylesheets to transform the JSON at export time (http://www.w3.org/TR/xslt-30/#json).

**Comment by pawal** [comment]
I tend to agree. After having giving this a lot of thought, I think that if the user really wants to have the JSON output structured differently, there are two options:

 - process the output afterwards
 - hooking the logger function, and do it properly beforehand

So, lets close this.

However, I think I found things in the log which might be errors from the modules - missing data, and not coherent naming of args.

Example:

      "args" : {
         "name" : "ns0.ja.net"
      },
      "module" : "SYNTAX",
      "tag" : "NAMESERVER_SYNTAX_OK",

Sometimes "name" is called "ns". I will create a new tickets for this instead.
