### ISSUE TITLE
Slightly confusing error message when no DS at parent

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#345]
When testing a signed domain with no DS published at the parent, the following message is logged:

    7.64 NOTICE    123.456.789.0 returned no DS records for example.com

For the user, this message is inconclusive. Does it mean that the parent simply does not have the DS record published, or that this particular name server does not have the DS published? (I know the answer, $user probably don't.)

**Comment by sandoche2k** [comment]
@pawal - move it to 2015.4

**Comment by pawal** [comment]
@sandoche2k We don't have a date set for 2015.4. Given the speed of releases, would it even be 2015?

**Comment by sandoche2k** [comment]
I do have the tentative dates here :
https://trello.com/b/Afo0A4Ib/zonemaster

But, i agree with you it seems difficult to complete everything in 2015. We
can decide the tentative dates during our F2F in Paris.

**Comment by sandoche2k** [comment]
@pawal  assign it to @vlevigneron ?

**Comment by sandoche2k** [comment]
we will be logging name and IP adress, which will provide a more conclusive response.
