### ISSUE TITLE
Warning while running make for zonemaster-cli

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster#346]
1. O.S : Ubuntu 14.10 (Clean install)
2. Zonemaster-engine already installed
3. After following the procedure for installing zonemaster-cli and running make, following results: [Warning shown using ****]
----------------------------
perl Makefile.PL
include /home/sandoche/zonemaster-cli/inc/Module/Install.pm
include inc/Module/Install/Metadata.pm
include inc/Module/Install/Base.pm
include inc/Module/Install/Makefile.pm
include inc/Module/Install/Scripts.pm
include inc/Module/Install/Share.pm
include inc/Module/Install/WriteAll.pm
include inc/Module/Install/Win32.pm
include inc/Module/Install/Can.pm
include inc/Module/Install/Fetch.pm
****Warning: prerequisite Zonemaster 0.0.4 not found.***
Generating a Unix-style Makefile
Writing Makefile for Zonemaster::CLI
Writing MYMETA.yml and MYMETA.json
Writing META.yml
---------------------

**Comment by sandoche2k** [comment]
In the previous message "Warning shown using ****" is "Warning highlighted"

**Comment by cdybedahl** [comment]
What do you get if you run `perl -MZonemaster -E 'say Zonemaster->VERSION'`?

**Comment by sandoche2k** [comment]
Pff.. I forgot make install..
