### ISSUE TITLE
GOST fails to validate

### ISSUE THREAD

**Issue by jschlyter** [dotse/zonemaster#347]
A zone signed with GOST fails to validate - http://zonemaster.net/test/4442.
Looking good with dnsviz - http://dnsviz.net/d/gost.nxdomain.se/dnssec/

Perhaps it's better if zonemaster says it cannot grok that algorithm instead of claiming it is broken?

Remember; Russian crypto is the best crypto.

**Comment by cdybedahl** [comment]
We already have a case open for this, but it doesn't hurt to have another domain to test with :-)
