### ISSUE TITLE
Selection of source address

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#352]
In the engine and the CLI, I would like to be able to select source address for queries going out. Similar to what Net::DNS do in Net::DNS::Resolver:

>   srcaddr
>           print 'sending queries from address ', $res->srcaddr, "\n";
>           $res->srcaddr('192.168.1.1');
>
>       Gets or sets the source address from which we send queries.  Convenient for forcing queries
>       out a specific interfaces on a multi-homed host.  The default is 0.0.0.0, meaning any local
>       address.

This should be available to the CLI as well.

(This is a request from registry services)

**Comment by cdybedahl** [comment]
Closed with the combination of dotse/net-ldns@3cbfa2ebf2caaf476019d2b2e57642512a91255f, dotse/zonemaster-cli@69300f586cea75760a7161bc96333cc140e66e60 and dotse/zonemaster-engine@567f2654d2e0a963d20eedb31a80638aac387cb4.
