### ISSUE TITLE
Comment on the installation instructions

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster#358]
@cdybedahl  - I know it trivial, but just want to inform

In the zonemaster-cli installation for Ubuntu, the first point where we install necessary packages, you have mentioned "sudo aptitude install ..."

But "aptitude" is not installed by default. Would you prefer to modify "aptitude" -> "apt-get" ?

**Comment by sandoche2k** [comment]
Also update the link for the backend "https://github.com/dotse/zonemaster-backend/blob/master/docs/installation.md"

**Comment by pawal** [comment]
Aptitude is not used in the current version?
