### ISSUE TITLE
Doubtful error message when the DS is dangling

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#362]
http://zonemaster.net/test/7189

``Found DS records with tags 37471.
No DNSKEYs were returned. ```

That is not really true, there are DNSKEY records. Simply, none for 37471 I suggest a better error message:

.``Found DS records with tags 37471.
No DNSKEYs matching the DS record(s) were returned. ```

**Comment by cdybedahl** [comment]
Like in the other issue you entered, Zonemaster gets a SERVFAIL response to its query for DNSKEYs, so it doesn't get any such RRs.

**Comment by pawal** [comment]
Why does Zonemaster receive a SERVFAIL? Does it validate the signatures?

**Comment by bortzmeyer** [comment]
@pawal Because there is a lame delegation. The server listed as authoritative (but which isn't) replies SERVFAIL.

.ke is an interesting case because several things are broken.
