### ISSUE TITLE
Wrong testing of the consistency parent/child

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#367]
mcdonalds.com has a discrepancy: the parent lists three name servers, the zone only two (bigmac1.mcd.com is missing) But Zonemaster does not detect it, quite the opposite http://zonemaster.net/test/7832 : 
All of the nameserver names are listed both at parent and child.

**Comment by cdybedahl** [comment]
Works for me:

```
Necronomicon-II:~% zonemaster-cli --test=Delegation mcdonalds.com
Seconds Level     Message
======= ========= =======
   4.66 WARNING   Nameserver bigmac1.mcd.com response is not authoritative on UDP port 53.
   4.94 WARNING   Nameserver bigmac1.mcd.com response is not authoritative on TCP port 53.
   6.96 ERROR     A SOA query NOERROR response from bigmac1.mcd.com was received empty.
   6.96 ERROR     Parent has nameserver(s) not listed at the child (bigmac1.mcd.com).
```

**Comment by bortzmeyer** [comment]
Or for me in CLI. Specific to the Web interface?

**Comment by cdybedahl** [comment]
Another test ran via the web interface gets the correct behavior. I wonder if the first, broken, test just managed to catch a transitional state. Note that it claims to have received a full three-member list of name servers from the child side, which I can't seem to get from any server now.

**Comment by pawal** [comment]
All seems to be in order.
