### ISSUE TITLE
Wrong TCP error message when TCP timeouts

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#369]
http://www.zonemaster.fr/test/8098

"Nameserver dns1.certa.ssi.gouv.fr response is not authoritative on TCP port 53. "

It  is not "not authoritative", it timeouts:

```
% dig @dns1.certa.ssi.gouv.fr SOA ssi.gouv.fr

; <<>> DiG 9.9.5-9-Debian <<>> @dns1.certa.ssi.gouv.fr SOA ssi.gouv.fr
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18807
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 3
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ssi.gouv.fr.           IN SOA

;; ANSWER SECTION:
ssi.gouv.fr.            300 IN SOA dns1.ssi.gouv.fr. resptech.ssi.gouv.fr. (
                                2015040901 ; serial
                                3600       ; refresh (1 hour)
                                1800       ; retry (30 minutes)
                                604800     ; expire (1 week)
                                3600       ; minimum (1 hour)
                                )

;; AUTHORITY SECTION:
ssi.gouv.fr.            300 IN NS dns1.ssi.gouv.fr.
ssi.gouv.fr.            300 IN NS dns1.certa.ssi.gouv.fr.

;; ADDITIONAL SECTION:
dns1.ssi.gouv.fr.       300 IN A 213.56.166.96
dns1.certa.ssi.gouv.fr. 300 IN A 213.56.176.3

;; Query time: 50 msec
;; SERVER: 213.56.176.3#53(213.56.176.3)
;; WHEN: Wed Apr 15 09:58:45 CEST 2015
;; MSG SIZE  rcvd: 161

% dig +tcp @dns1.certa.ssi.gouv.fr SOA ssi.gouv.fr

; <<>> DiG 9.9.5-9-Debian <<>> +tcp @dns1.certa.ssi.gouv.fr SOA ssi.gouv.fr
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by pawal** [comment]
This is probably a bug in the test specifications, more specifically both CONNECTIVITY01 and CONNECTIVITY02. It does not take into account any timeouts. It should check for the aa flag, and when there is no aa flag in the "answer", find out if it was a timeout, or if the address was actually responding something.

Thus, this needs an updated test specification, and implementation.

**Comment by sandoche2k** [comment]
@pawal - Rather i think the modification should be made at delegation04.md. In that case, other test specifications at delegation should also undergo a timeout test (or), this should be run only after successful connectivity tests.
@sandoche2k - Once confirmed, update the test specification
@vlevigneron - Once the test specification is updated, implementation

**Comment by sandoche2k** [comment]
@bortzmeyer @pawal 

I think the issue is in "Delegation04" (https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Delegation-TP/delegation04.md)  and it should be updated

**The error is "Nameserver dns1.certa.ssi.gouv.fr response is not authoritative on TCP port 53"**

I suggest to modify the specification as follows :
1. Obtain the complete set of name servers from the parent using Method2 and the child using Method3.
2. All name servers are queried for the SOA record over TCP and UDP on port 53
3. **For each query in step 2, check whether DNS answer (bogus response are not checked here) is obtained. If any of the query fails, then do not proceed to step 4 for that query. **
4. If any name server fail to give an authoritative answer ("AA-bit" is set in the answer), then the test fails.

**Comment by sandoche2k** [comment]
It looks good, I think. Basically it moves a possible false-positive (report a problem when there may not be one) to a possible false-negative (do not report a problem when there is one). In this case, that is definitely preferable.
It does occur to me, though, that this is actually an instance of a larger issue that we as a group failed to think of. All our test specifications implicitly assume that queries get responses. We don’t ever say what should happen in the case where the tests don’t get the responses they need to determine their outcome. Differently put, all our tests are based on “pass or fail” thinking (with lots of details on exactly how things pass or fail), while in reality that should be “pass, fail or undetermined”. Consider for example the case of running Zonemaster on a machine with no network connection. Today, that gives a very long list of “fail” messages. It would make much more sense if all the tests that rely on DNS queries could instead return “undetermined”.
Fixing that is a huge job, though, so it certainly won’t happen any time soon. But I think it would be good to put it on the wishlist for Zonemaster 2.0.

**Comment by sandoche2k** [comment]
@vlevigneron close?

**Comment by sandoche2k** [comment]
@vlevigneron - check and close

**Comment by vlevigneron** [comment]
Implementation has not been updated unlike the specifications.
I'll fix it ASAP.
