### ISSUE TITLE
Support for uppercase/lowercase queries (0x20) 

### ISSUE THREAD

**Issue by pettai** [dotse/zonemaster#372]
Hi,

It would be useful if zonemaster supported 0x20 queries (uppercase/lowercase mixed zone names)
We're still seeing some problem domains/nameservers that aren't RFC complaint in that partical case...
First that comes to mind is LinkedIn's CDN provider(s): static.licdn.com

Re,
/P

**Comment by pawal** [comment]
Added this in requirements. This is a duplicate of #313, will close #313 now.

A reference for this test case is in section 7.1, RFC 1035.

**Comment by sandoche2k** [comment]
@pawal move it to 2015.3.

**Comment by sandoche2k** [comment]
@pawal i tested various combinations below:  
   
   www.ietf.org
   WWW.IETF.ORG
   WwW.iEtF.oRg
   wWw.IeTf.OrG

It seems working with the zonemaster-cli. Thanks for clarifying what is still to be done?

**Comment by pawal** [comment]
A test should be implemented to check for explicit protocol compliance. Yes, this works since this is how DNS works. But we don't have a test case for it.

**Comment by sandoche2k** [comment]
Ok i will write one

**Comment by sandoche2k** [comment]
@vlevigneron test spec written -nameserver08.md

**Comment by sandoche2k** [comment]
@vlevigneron We did discuss during the F2F. I think this issue has been implemented. Can you verify and close?

**Comment by sandoche2k** [comment]
@vlevigneron - normally u have full access rights now. Can you verify and close?

**Comment by vlevigneron** [comment]
I was able to merge. Verified and closed...
