### ISSUE TITLE
Should warn when a RRset cannot be transmitted over UDP?

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#375]
With the typical EDNS setup of name servers (4096 bytes), some RRsets cannot be transferred over UDP (see the DNSKEY RRset of hccforums.nl) and require a switch to TCP which may fail (broken middleboxes, etc). Zonemaster does not warn about that: http://zonemaster.net/test/9819 May be it should?

**Comment by sandoche2k** [comment]
Discuss this and if we think that this is a requirement that we need to ponder upon, we should move this to atleast to 2015.4 @pawal

**Comment by sandoche2k** [comment]
@VLE - log when the response is more then 4096 bytes. It should be done at the engine. No test specification needed.
