### ISSUE TITLE
Filters - RIPE requirement 

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster#376]
Anand Buddev from RIPE requested the possibility of exempting certain name servers from being tested during DNS validation. This feature is already present in DNScheck.

**Comment by einar** [comment]
Plz clarify, not sure what feature in DNSCheck this is? Both tools can exempt when running undelegated; afaik neither can exempt a normal run.

**Comment by sandoche2k** [comment]
Anand Budhdev from RIPE mentioned that he can exempt certain nameservers
for a domain name being tested using DNScheck.

For example if you are testing afnic.fr and if you are putting a filter on
a nameserver e.g. ns1.nic.fr, the tool will be testing only with the other
nameservers such as ns2, ns3 etc..

**Comment by einar** [comment]
Could Anand provide an exemple CLI-flag using this? I think he's using undelegated and just omitting the NS he doesnt want to test, otherwise I have no clue what he's doing as there are no such features I'm aware of in DNSCheck.

**Comment by sandoche2k** [comment]
In that case, it is present in ZM too. But, Patrik mentioned during the
presentation that we do not have in ZM as of now.

So, i felt that it is a different feature.

**Comment by einar** [comment]
I think he forgot about undelegated... ;) With a twist it's easy to fulfill most filter requirements using undelegated-functionality. But I'm *very* curious so plz ask Anand as I guess he's at RIPE? :)

**Comment by sandoche2k** [comment]
I will do that.

**Comment by pawal** [comment]
The code for it is in the DNSCheck::Logger module. Read the POD for that.

**Comment by sandoche2k** [comment]
@pawal Move it to 2015.3?

**Comment by cdybedahl** [comment]
The functionality in DNSCheck that Anand is using doesn't actually prevent tests from running against certain servers, it only filters out log entries related to them. I believe equivalent functionality already exists in the Zonemaster engine, but I'll have a look and if needed write some documentation on how to migrate from DNSCheck.

**Comment by cdybedahl** [comment]
Exactly the same kind of functionality as in DNSCheck already exists in Zonemaster, and is described in the `Zonemaster::Config` documentation under the heading `logfilter`. It should be easy enough to move a DNSCheck configuration over to Zonemaster using only the existing documentation, so I will close this case. If I'm wrong and it is some other functionality that's meant, or the documentation is not clear enough, please make another issue with more specific information about the problem

**Comment by pawal** [comment]
Thank you, I will let them know.
