### ISSUE TITLE
Suspected Bug (Nial O'Reilly)

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster#379]
Please see Zonemaster report for IE zone
  (http://zonemaster.net/test/13004), which shows:

There is no misused '@' character in the SOA RNAME field (tld-tech.iedr.ie.).
 
The SOA RNAME field (tld-tech@iedr.ie) is compliant with RFC2822.

[...]

No target (MX, A or AAAA record) to deliver e-mail for the domain name.

Zonemaster Version: 1.0.0, IP address: 87.192.78.152

  I have no difficulty retrieving MX, A, and AAAA records for iedr.ie.
  For example, after priming my local resolver with specific queries,
  I can see the following:

dhcp-162(niall)27: dig iedr.ie. any | awk '($4=="AAAA" || $4=="A" || $4=="MX")'
iedr.ie.		191	IN	A	193.1.32.49
iedr.ie.		3600	IN	MX	10 titan02.iedr.ie.
iedr.ie.		3600	IN	MX	10 titan01.iedr.ie.
iedr.ie.		191	IN	AAAA	2001:770:d0:1::49
ns0.iedr.ie.		2498	IN	A	193.1.32.61
ns0.iedr.ie.		2498	IN	AAAA	2001:770:d0:1::37
ns2.iedr.ie.		2498	IN	A	83.71.193.88
titan01.iedr.ie.	709	IN	A	83.71.193.66
titan02.iedr.ie.	2509	IN	A	193.1.253.24
dhcp-162(niall)28: 

  I can also reach titan01.iedr.ie on TCP port 25.

  I wonder why Zonemaster is reporting "No target [...]".

**Comment by pawal** [comment]
No target means that there is no way for SMTP to deliver any mail to any address at @ie. Which is correct. We are not testing connectivity for port 25.

**Comment by sandoche2k** [comment]
@pawal  Can we close it?

**Comment by pawal** [comment]
On 26 May 2015, at 13:54, sandoche2k <notifications@github.com> wrote:

> @pawal Can we close it?

Yes.
