### ISSUE TITLE
Cannot test the Yeti root: Zonemaster keeps using the Verisign one

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#381]
I tried testing the [Yeti root](http://yeti-dns.org) but Zonemaster produces  spurious error messages referring to the Verisign root name servers:

Nameserver a.root-servers.net response is not authoritative on UDP port 53.

or

A SOA query NOERROR response from a.root-servers.net was received empty. 

See http://zonemaster.net/test/13373

**Comment by bortzmeyer** [comment]
The CLI gives the same thing:

```
  29.67 WARNING   Nameserver m.root-servers.net response is not authoritative on TCP port 53.
  29.81 ERROR     A SOA query NOERROR response from a.root-servers.net was received empty.
```

**Comment by cdybedahl** [comment]
This is an "Out of scope" thing, really. As in, "Zonemaster is not intended to be able to do that".

The root zone is enough of a special case that we have in several cases so far simply accepted that running Zonemaster on it does not give sensible results. What you're running into here, more specifically, is that the built-in recursor in Zonemaster always starts from a hardcoded list of root servers. The code that fakes information for undelegated tests kick in slightly later in the process.

It is of course possible to add the ability to switch out the root hints list, but it's a not insignificant amount of work (mostly in testing that it doesn't break anything) and I'm not sure if it's worth it given that we already know that the results of testing root(s) are dodgy. My suggestion right now is that we put "Work on and with different root zones" on the wishlist for a future version, and let the people assigning the resources decide if and when it should be implemented.

If a third party were to want to contribute work in this direction, I think the start should be to work out a policy file that only includes those tests that actually make sense on a root zone. Most of the Delegation module probably doesn't, for example.

**Comment by pawal** [comment]
I think we should list this as a known issue. By the way, having a look at the know issue file for the engine reveals to me that there are some things fixed there.

In the long term, we should definitely fix this problem, as one of our main use cases is testing TLDs, and this also includes the arpa zone.

**Comment by bortzmeyer** [comment]
@cdybedahl In that case, as a minimum, Zonemaster must emits a clear message "Testing the root zone is not implemented"

**Comment by cdybedahl** [comment]
I'm adding a notice about it to the KNOWN_ISSUES file, but for a runtime error message there should be a specification change first.

**Comment by sandoche2k** [comment]
@pawal milestone and assignee please...

**Comment by sandoche2k** [comment]
@pawal - i think we can move it to the icebox..?

**Comment by sandoche2k** [comment]
@pawal  - move to the next release ..

**Comment by bortzmeyer** [comment]
Here, with the CLI, which has the same issue. The machine uses Yeti:

```
% dig NS .
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 10049
;; Flags: qr rd ra; QUERY: 1; ANSWER: 14; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; .                   		IN	NS

;; ANSWER SECTION:
.                   	318290	IN	NS	bii.dns-lab.net.
.                   	318290	IN	NS	yeti.bofh.priv.at.
.                   	318290	IN	NS	yeti.ipv6.ernet.in.
.                   	318290	IN	NS	yeti.aquaray.com.
.                   	318290	IN	NS	dahu1.yeti.eu.org.
.                   	318290	IN	NS	dahu2.yeti.eu.org.
.                   	318290	IN	NS	ns-yeti.bondis.org.
.                   	318290	IN	NS	yeti-ns.ix.ru.
.                   	318290	IN	NS	yeti-ns.tisf.net.
.                   	318290	IN	NS	yeti-ns.wide.ad.jp.
.                   	318290	IN	NS	yeti-ns.conit.co.
.                   	318290	IN	NS	yeti-ns.switch.ch.
.                   	318290	IN	NS	yeti-ns.as59715.net.
.                   	318290	IN	NS	yeti-dns01.dnsworkshop.org.

;; Received 428 B
;; Time 2015-10-31 02:17:47 UTC
;; From 127.0.0.1@53(UDP) in 0.3 ms
```

But ZoneMaster tests the wrong root:

```
% zonemaster-cli .
Seconds Level     Message
======= ========= =======
  18.55 WARNING   Nameserver b.root-servers.net has an IP address (2001:500:84::b) without PTR configured.
  72.72 NOTICE    198.41.0.4 returned no DS records for ..
  72.94 WARNING   198.41.0.4 sent a DNSKEY record, but 198.41.0.4 did not send a DS record.
  75.41 NOTICE    Delegation from parent to child is not properly signed (no_ds).
  78.51 ERROR     Nameserver a.root-servers.net/198.41.0.4 is a recursor.
  78.58 ERROR     Nameserver a.root-servers.net/2001:503:ba3e::2:30 is a recursor.
  78.70 ERROR     Nameserver b.root-servers.net/192.228.79.201 is a recursor.
  78.85 ERROR     Nameserver b.root-servers.net/2001:500:84::b is a recursor.
...
```

**Comment by sandoche2k** [comment]
@bortzmeyer we will close this issue as this is out of scope for us as of now
