### ISSUE TITLE
Why forcing the user to mention the glue?

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#382]
I try to test a non-standard zone with the CLI so I use the --ns options:

```
% zonemaster-cli  --ns bii.dns-lab.net --ns  yeti-ns.tisf.net --ns yeti-ns.wide.ad.jp --ns yeti-ns.as59715.net --ns dahu1.yeti.eu.org .
Seconds Level     Message
======= ========= =======
Malformed --ns switch, need name and IP separated by a /.
```

Why forcing the user to indicate the glue? All these names are perfectly resolvable.

**Comment by cdybedahl** [comment]
Because I didn't think of the use case of redirecting to already existing servers when I wrote it. I'll be creating a pull request with a fix in a moment.

**Comment by sandoche2k** [comment]
@bortzmeyer Can you verify .. so that we can close this issue.

**Comment by bortzmeyer** [comment]
On Wed, Jun 03, 2015 at 10:56:25PM -0700,
 sandoche2k <notifications@github.com> wrote 
 a message of 28 lines which said:

> @bortzmeyer Can you verify .. so that we can close this issue.

Seems OK, I just tested .sncf that way
<http://zonemaster.net/test/14912>, by giving just the name of one
name server.

[But I do not understand the DNSSEC error.]

**Comment by pawal** [comment]
The GUI currently lacks the functionality to add a pre-delegated DS record. And the engine will fake all data coming from the parent with the input given for the test, so that is why you see a missing DS record.
