### ISSUE TITLE
Please add IDN support to the zonemaster

### ISSUE THREAD

**Issue by samm-git** [dotse/zonemaster#383]
It would be great to add IDN support to the zonemaster, because non-english domain names are very widespread today, especially in countries with non-latin alphabets (Cyrillic, Chinese, etc.). When i am trying to check http://домен.укр/ i am getting "Can't get syntax test result" reply instead of IDN check of the http://xn--d1acufc.xn--j1amh domain. 
There are some IDN implementations in CPAN (e.g. http://search.cpan.org/~cfaerber/Net-IDN-Encode-2.202/lib/Net/IDN/Encode.pm) so this should not be a hard task to implement.

**Comment by pawal** [comment]
The CLI has support for IDN if Net::LDNS was compiled with libidn. However, the web interface does not support IDN.

**Comment by samm-git** [comment]
Thank you for reply, i tested only with web interface yet. BTW, there is also punnycode implementation in JS (https://github.com/bestiejs/punycode.js/) if you dont want to pass UTF to the backend.

**Comment by samm-git** [comment]
JFYI: i cant confirm that zonemaster-cli works with idn. Below is result from FreeBSD VM:
```
root@bsd10:~ # zonemaster-cli домен.укр
Seconds Level     Message
======= ========= =======
Error: String preparation failed
```

**Comment by mtoma** [comment]
The Web interface supports IDN. 
At least it did support it before the last release...
Rollback of the Fronend as Well?

----- Original Message -----

**Comment by cdybedahl** [comment]
Nothing relating to domain names was changed in the GUI, so that should work exactly as before. But it's curious that the CLI tries to turn the given name into punycode and fails. I'll be looking into it this week.

**Comment by patrikhson** [comment]
On 1 Jun 2015, at 8:56, Calle Dybedahl wrote:

> Nothing relating to domain names was changed in the GUI, so that should work exactly as before. But it's curious that the CLI tries to turn the given name into punycode and fails. I'll be looking into it this week.

I think one of the tests that should be made is to validate that the string given is valid. Either valid ULABEL or valid ALABEL. So the code should be stable enough to get an invalid IDN regardless of what format it is given in. If the string is an invalid ALABEL, the tests could continue.

   paf

**Comment by cdybedahl** [comment]
The test engine only works on ALABELs, it's up to the code using the engine to handle all messy character encoding stuff. There is a support function available to convert from internal Perl character representation to ALABEL, but the step from a name in an entirely unknown environment to internal Perl encoding is impossible to reliably generalize.

In this case, the problem in the CLI turns out to be simple and embarrassing, in that I have failed to properly use an API that I myself designed and implemented (it fed octets with the UTF-8 representation of the name to the helper function mentioned above, rather than the expected Perl character data). I'll be making a pull request with a fix shortly.

**Comment by sandoche2k** [comment]
@samm-git  It works after the correction. from the CLI Thanks for your input. Can you chck and configrm 

zonemaster-cli café.fr
Seconds Level     Message
======= ========= =======
   8.16 WARNING   All nameservers IPv4 addresses are in the same AS (16509).
   8.16 WARNING   All nameservers are in the same AS (16509).
   8.18 NOTICE    192.5.4.2 returned no DS records for xn--caf-dma.fr.
   8.34 NOTICE    Delegation from parent to child is not properly signed (no_ds).
sandoche@eryx:~/Git/sandoche/zonemaster-cli$ zonemaster-cli президент.рф
Seconds Level     Message
======= ========= =======
  10.54 WARNING   Nameserver ns2.gov.ru has an IP address (194.226.127.210) without PTR configured.
  23.23 ERROR     Nameserver ns.gov.ru/95.173.128.77 not accessible over TCP on port 53.
  33.24 ERROR     Nameserver ns2.gov.ru/194.226.127.210 not accessible over TCP on port 53.
  36.84 WARNING   All nameservers IPv6 addresses are in the same AS (42385).
  36.92 NOTICE    193.232.128.6 returned no DS records for xn--d1abbgf6aiiy.xn--p1ai.
  37.32 NOTICE    Delegation from parent to child is not properly signed (no_ds).
  37.34 WARNING   Nameserver ns.gov.ru response is not authoritative on TCP port 53.
  37.34 WARNING   Nameserver ns2.gov.ru response is not authoritative on TCP port 53.
  52.96 NOTICE    SOA 'refresh' value (10800) is less than the recommended one (14400)

**Comment by sandoche2k** [comment]
@mtoma If the issue was only in the CLI, why did it not work from the WebUI?

**Comment by pawal** [comment]
Testing räksmörgås.se in the CLI works for me now. Had to recompile Net::LDNS with IDN support first. :)
:+1: 

(Testing домен.укр also works...)

**Comment by sandoche2k** [comment]
I just did a pull request with the current modification by Calle and as
usual make, make install with the CLI.

**Comment by cdybedahl** [comment]
It looks like the web backend has very similar bugs in two places. I'm working on it.

**Comment by samm-git** [comment]
After applying patch from https://github.com/dotse/zonemaster-cli/pull/18 IDN in CLI works for me, thanks :+1:

**Comment by mtoma** [comment]
No idea.
The only thing I know is that I have plenty non ascii domains in the database with a 100% test completion result.
This is what I call unnecessary risks when redesigning code.

----- Original Message -----

**Comment by samm-git** [comment]
JFYI - it seems that non-js interface works fine with IDN names, so probably it is JS error:
http://www.zonemaster.net/nojs?test_id=14342

**Comment by cdybedahl** [comment]
> On 1 jun 2015, at 17:59, mtoma <notifications@github.com> wrote:
> 
> No idea.

You have repeatedly and very firmly claimed that this code is so short and simple that there cannot possibly be any problems maintaining it. If that is the case, why can’t you tell what’s going on here?

> The only thing I know is that I have plenty non ascii domains in the database with a 100% test completion result.
> This is what I call unnecessary risks when redesigning code.


Properly written software has unit tests that detect if anything existing breaks when code is changed or added.
Software that cannot have code added or changed will quickly become obsolete as reality changes around it.

— 
Calle Dybedahl
calle.dybedahl@init.se

**Comment by cdybedahl** [comment]
I have submitted pull requests against Backend and GUI that should fix the IDN problems.

**Comment by sandoche2k** [comment]
@Michal

Do you think we could test it in a separate machine (with the same
environment as the one in production) before integrating?

Sandoche.

**Comment by mtoma** [comment]
I have no idea for one simple reason: I did not look at it. Neither tried to find the problem.
It is the responsibility of the person who writes the software to deliver working software.
I was busy "undeleting" the cron scripts that were simply deleted ignoring my very firm requirement to be able to run the software in the same way as I was doing it before the backend+frontend redesign. 


----- Original Message -----

**Comment by sandoche2k** [comment]
Dear all,

   Can we move forward in testing the version that is currently released.
Michal is it possible to have a set up ready.

Sandoche.

**Comment by mtoma** [comment]
I can set up a separate frontend on port 5080 easily and quickly, the port is already opened for everyone so it shouldn't be any kind of problem.
For the backend it requires some more work as I need to setup a separate environment and probably add some code to allow to run all the backend parts with a specific configuration file.
Additionally we should have 3 separate frontend+backend setups each one for each of the 3 backend databases. 

----- Original Message -----

**Comment by mtoma** [comment]
By the way what do you mean by "the version that is currently released"?
Is it the latest version with the latest commits or the 1.0.2 release that could not be put in production last time?

----- Original Message -----

**Comment by sandoche2k** [comment]
Thanks Michal.

But why three. Isn't is two?

The second only is just for us to test.

Sandoche.

**Comment by sandoche2k** [comment]
I meant latest version with latest commits.

**Comment by cdybedahl** [comment]
> On 2 jun 2015, at 11:07, mtoma <notifications@github.com> wrote:
> 
> I have no idea for one simple reason: I did not look at it. Neither tried to find the problem.


I’m not sure I understand you correctly. This is a project. It is a *group* effort. Are you saying that you’re not even trying to help make the group succeed?

— 
Calle Dybedahl
calle.dybedahl@init.se

**Comment by mtoma** [comment]
Well, you got one part right.
"This is a project" a project for me means:
- a planning
- budget
Nowhere in my planning I have space to fix this issue.
What would be your advice here to allow me to help the group succeed? 

----- Original Message -----

**Comment by pawal** [comment]
On 02 Jun 2015, at 12:44, sandoche2k <notifications@github.com> wrote:

> I meant latest version with latest commits.

I have no problem with a new release for this, if that is what is required.

**Comment by sandoche2k** [comment]
I think Patrik, before we qualify it as a release with a new release
number, i think we should test it.

Correct me if you feel otherwise.

**Comment by pawal** [comment]
It passes make test, and I have tested the fixes. I have also run a number of other tests.
What kind of other tests are you referring to?

**Comment by sandoche2k** [comment]
For example for this issue, it works, when a IDN domain is provided as
input to the Web interface.

**Comment by sandoche2k** [comment]
@mtoma this issue could be closed, if you integrate the pull request by calle
