### ISSUE TITLE
Benchmark the quality of tests and test specifications 

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster#385]
from @pawal validate the quality of the tests and test specification, so we need more benchmarking with the tools that is the requirements for Zonemaster.

**Comment by sandoche2k** [comment]
@pawal - Further discussion on what needs to be done has to be discussed. Can you move it to .3

**Comment by sandoche2k** [comment]
To Note : Consistency testing with ZC and DC

**Comment by sandoche2k** [comment]
@pawal we need a detailed benchmark if in case we are running the tests comparing each of the test specifications. At this moment i am closing it.

**Comment by patrikhson** [comment]
Hello,

Me and my family have visited a very cozy place recently, you may really like it, just take a look at some pics of it <http://stikucucro.ericgratz.com/xypsnsa>

Best regards, paf@frobbit.se
