### ISSUE TITLE
Useless test xx--illegal-syntax-tld

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#386]
```
% zonemaster-cli stratcom.mil
...
   9.49 ERROR     Nameserver kingfisher1.stratcom.mil/143.250.3.75 answered with a RCODE NXDOMAIN to SOA query on xx--domain-cannot-exist.xx--illegal-syntax-tld.
```

This name is not illegal (it is an illegal *machine* name, not an illegal *domain* name and I don't think authoritative name servers should enforce this rule.

In the mean time, this name server has a more serious problem, it replies NXDOMAIN (with aa and ra...) to a
request for a domain it is not authoritative for. Zonemaster could test that.

**Comment by cdybedahl** [comment]
That is test case [nameserver01](https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Nameserver-TP/nameserver01.md). The name `xx--domain-cannot-exist.xx--illegal-syntax-tld` is used as a name that is extremely unlikely to be a proper existing name.

**Comment by bortzmeyer** [comment]
Then, the error message is utterly confusing, because it has no relationship with the test case.

**Comment by cdybedahl** [comment]
That I agree with. Feel free to add an issue for that :-)

**Comment by cdybedahl** [comment]
No, wait, there already is one, dotse/zonemaster-engine#76
