### ISSUE TITLE
Team Cymru link

### ISSUE THREAD

**Issue by cdybedahl** [dotse/zonemaster#387]
Team Cymru, who we get our IP-to-ASN data from, have a [link to DNSCheck](http://www.team-cymru.org/IP-ASN-mapping.html) on one of their web pages. At some point someone should probably contact them and ask them to change that to Zonemaster instead.

**Comment by sandoche2k** [comment]
@pawal - will contact team cymru about this issue

**Comment by sandoche2k** [comment]
@pawal - didn't we say that we will have our own server and we will not depend upon "Team Cymru" anymore. If that's correct please close this issue and open another one.

**Comment by pawal** [comment]
We get our data from Cymru, but we are not relying on their servers.

**Comment by sandoche2k** [comment]
@pawal https://github.com/dotse/zonemaster/issues/464 fixes it
