### ISSUE TITLE
Distracting error message when a name server refuses to answer

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#397]
Context: a zone where one name server is not configured to serve the zone, and replies REFUSED (see https://zonemaster.net/test/17149 )

Zonemaster correctly says "Nameserver ns-ext.nlnetlabs.nl/185.49.140.62 did not return NS records. RCODE was REFUSED. "

But it also, in the DNSSEC group, says "Server at 185.49.140.62 sent 0 DNSKEY records, and 0 RRSIG records. " This is distracting since, it is just a consequence of the previous problem.

**Comment by sandoche2k** [comment]
@bortzmeyer - We are not able to reproduce the error. Thanks for pointing out to any domain which has similar issue.

**Comment by sandoche2k** [comment]
@bortzmeyer will be repoened if we can reproduce the error
