### ISSUE TITLE
"Unknown error" when all the NS refuse to answer

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#405]
All three name servers of sympa.org reply REFUSED. Zonemaster does not handle it well: "Unknown error while checking for domain existance"

**Comment by pawal** [comment]
Well, it handles it well, but the message could be more clear. It should state that no nameserver is reachable, and further testing can not be performed.

**Comment by bortzmeyer** [comment]
On Mon, Jun 29, 2015 at 03:45:39AM -0700,
 Patrik Wallström <notifications@github.com> wrote 
 a message of 28 lines which said:

> Well, it handles it well, but the message could be more clear. It
> should state that no nameserver is reachable,

They are reachable. No need to investigate a routing problem. I
suggest a message like "All authoritative name servers for this domain
$DOMAIN returns REFUSED. No further testing possible."

**Comment by sandoche2k** [comment]
@bortzmeyer https://zonemaster.net/test/37218 - Can this issue be closed ?

**Comment by bortzmeyer** [comment]
OK
