### ISSUE TITLE
Problems with installing zone master (Net::LDNS dependency)

### ISSUE THREAD

**Issue by nyczrok** [dotse/zonemaster#409]
Thanks for all your efforts with zonemaster. My apologies if it's not a right place to ask my question. I tried to install zonemaster but I have a problem with the Net::LDNS dependency. I found a corresponding post https://bugzilla.redhat.com/show_bug.cgi?id=1190724 but it didn't help me in solving the problem.

Here are partial logs:
root@machine1: uname -a
Linux machine1 3.2.0-4-amd64 #1 SMP Debian 3.2.60-1+deb7u3 x86_64 GNU/Linux

root@machine1:~/.cpan/sources/authors/id/I/II/IIS/Zonemaster-v1.0.4# sudo cpan -i Zonemaster

...

Test Summary Report
-------------------
t/axfr.t         (Wstat: 29440 Tests: 1 Failed: 0)
  Non-zero exit status: 115
  Parse errors: No plan found in TAP output
Files=13, Tests=218,  6 wallclock secs ( 0.07 usr  0.02 sys +  0.54 cusr  0.06 csys =  0.69 CPU)
Result: FAIL
Failed 1/13 test programs. 0/218 subtests failed.
make: *** [test_dynamic] Error 255
  CDYBED/Net-LDNS-0.75.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports CDYBED/Net-LDNS-0.75.tar.gz
Running make install
  make test had returned bad status, won't install without force
Running make for I/II/IIS/Zonemaster-v1.0.4.tar.gz
  Has already been unwrapped into directory /root/.cpan/build/Zonemaster-v1.0.4-ZCeJZw

  CPAN.pm: Going to build I/II/IIS/Zonemaster-v1.0.4.tar.gz

Warning: Prerequisite 'Net::LDNS => 0.75' for 'IIS/Zonemaster-v1.0.4.tar.gz' failed when processing 'CDYBED/Net-LDNS-0.75.tar.gz' with 'make_test => NO'. Continuing, but chances to succeed are limited.
cp lib/Zonemaster/TestMethods.pm blib/lib/Zonemaster/TestMethods.pm
cp lib/Zonemaster/Nameserver.pm blib/lib/Zonemaster/Nameserver.pm
cp lib/Zonemaster/Test/Connectivity.pm blib/lib/Zonemaster/Test/Connectivity.pm
cp lib/Zonemaster/Test/Syntax.pm blib/lib/Zonemaster/Test/Syntax.pm
cp lib/Zonemaster/Test/Example.pm blib/lib/Zonemaster/Test/Example.pm
cp lib/Zonemaster/Logger.pm blib/lib/Zonemaster/Logger.pm
cp lib/Zonemaster/Translator.pm blib/lib/Zonemaster/Translator.pm
cp lib/Zonemaster/Test/Basic.pm blib/lib/Zonemaster/Test/Basic.pm
cp lib/Zonemaster/Test/Nameserver.pm blib/lib/Zonemaster/Test/Nameserver.pm
cp lib/Zonemaster/NSArray.pm blib/lib/Zonemaster/NSArray.pm
cp lib/Zonemaster/Exception.pm blib/lib/Zonemaster/Exception.pm
cp lib/Zonemaster/Test/Delegation.pm blib/lib/Zonemaster/Test/Delegation.pm
cp lib/Zonemaster/Util.pm blib/lib/Zonemaster/Util.pm
cp lib/Zonemaster/Test/DNSSEC.pm blib/lib/Zonemaster/Test/DNSSEC.pm
cp lib/Zonemaster/DNSName.pm blib/lib/Zonemaster/DNSName.pm
cp lib/Zonemaster/Packet.pm blib/lib/Zonemaster/Packet.pm
cp lib/Zonemaster/Zone.pm blib/lib/Zonemaster/Zone.pm
cp lib/Zonemaster/Recursor.pm blib/lib/Zonemaster/Recursor.pm
cp lib/Zonemaster/Nameserver/Cache.pm blib/lib/Zonemaster/Nameserver/Cache.pm
cp lib/Zonemaster/Overview.pod blib/lib/Zonemaster/Overview.pod
cp lib/Zonemaster/Test/Address.pm blib/lib/Zonemaster/Test/Address.pm
cp lib/Zonemaster/Test/Consistency.pm blib/lib/Zonemaster/Test/Consistency.pm
cp lib/Zonemaster/Config.pm blib/lib/Zonemaster/Config.pm
cp lib/Zonemaster/ASNLookup.pm blib/lib/Zonemaster/ASNLookup.pm
cp lib/Zonemaster/Test.pm blib/lib/Zonemaster/Test.pm
cp lib/Zonemaster.pm blib/lib/Zonemaster.pm
cp lib/Zonemaster/Test/Zone.pm blib/lib/Zonemaster/Test/Zone.pm
cp lib/Zonemaster/Constants.pm blib/lib/Zonemaster/Constants.pm
cp lib/Zonemaster/Logger/Entry.pm blib/lib/Zonemaster/Logger/Entry.pm
Manifying 29 pod documents
  IIS/Zonemaster-v1.0.4.tar.gz
  /usr/bin/make -- OK
Running make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ............ 1/? Bailout called.  Further testing stopped: 

#   Failed test 'use Zonemaster;'
#   at t/00-load.t line 9.
#     Tried to use 'Zonemaster'.
#     Error:  Can't locate Net/LDNS.pm in @INC (@INC contains: /root/.cpan/build/Zonemaster-v1.0.4-ZCeJZw/inc /root/.cpan/build/Zonemaster-v1.0.4-ZCeJZw/blib/lib /root/.cpan/build/Zonemaster-v1.0.4-ZCeJZw/blib/arch /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /root/.cpan/build/Zonemaster-v1.0.4-ZCeJZw/blib/lib/Zonemaster/Nameserver.pm line 13, <DATA> line 1.
# BEGIN failed--compilation aborted at /root/.cpan/build/Zonemaster-v1.0.4-ZCeJZw/blib/lib/Zonemaster/Nameserver.pm line 13, <DATA> line 1.
# Compilation failed in require at /root/.cpan/build/Zonemaster-v1.0.4-ZCeJZw/blib/lib/Zonemaster.pm line 6, <DATA> line 1.
# BEGIN failed--compilation aborted at /root/.cpan/build/Zonemaster-v1.0.4-ZCeJZw/blib/lib/Zonemaster.pm line 6, <DATA> line 1.
# Compilation failed in require at (eval 4) line 2, <DATA> line 1.
# BEGIN failed--compilation aborted at (eval 4) line 2, <DATA> line 1.
# Testing Zonemaster v1.0.4, Perl 5.014002, /usr/bin/perl
# Looks like you failed 1 test of 1.
FAILED--Further testing stopped.
make: *** [test_dynamic] Error 1
  IIS/Zonemaster-v1.0.4.tar.gz
one dependency not OK (Net::LDNS); additionally test harness failed
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports IIS/Zonemaster-v1.0.4.tar.gz
Running make install
  make test had returned bad status, won't install without force

------------------------------------------------------------------------------------------------

root@machine1:~/.cpan/sources/authors/id/I/II/IIS/Zonemaster-v1.0.4# perl Makefile.PL 
Warning: prerequisite Net::LDNS 0.75 not found.
Generating a Unix-style Makefile
Writing Makefile for Zonemaster
Writing MYMETA.yml and MYMETA.json

Thanks for your support,

best,
nyczrok

**Comment by pawal** [comment]
Hi,

Thanks for your report.

Which OS and version are you using?

**Comment by nyczrok** [comment]
Hi,

Thank you for the quick reply and sorry for not being precise enough. It's Debian Wheezy. Please let me know if I could provide you with any further information.

root@machine1:~$ uname -a
Linux provolone 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u2 x86_64 GNU/Linux
root@machine1:~$ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"

Thank you,
nyczrok

**Comment by pawal** [comment]
I will try to replicate toe issue today with a clean Wheezy machine.

**Comment by pawal** [comment]
Following the installation instructions on a clean install of Debian 7.8.0 amd64 on my virtual machine gave me a proper install of Net::LDNS and Zonemaster.

Relevant log output from my test:

```
Running Mkbootstrap for Net::LDNS ()
chmod 644 "LDNS.bs"
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/*.t
t/axfr.t ........... ok
t/dnssec.t ......... ok
t/idn.t ............ ok
t/load_zonefile.t .. ok
t/netldns.t ........ ok
t/packet.t ......... ok
t/regression.t ..... ok
t/resolver.t ....... ok
t/rr.t ............. ok
t/rrlist.t ......... ok
t/serialize.t ...... ok
t/threads.t ........ ok
t/utils.t .......... ok
All tests successful.
Files=13, Tests=221,  5 wallclock secs ( 0.16 usr  0.03 sys +  0.86 cusr  0.18 csys =  1.23 CPU)
Result: PASS
  CDYBED/Net-LDNS-0.75.tar.gz
  /usr/bin/make test -- OK
Running make install
```

Could you explain your setup?

**Comment by nyczrok** [comment]
The installation problem resolved! My firewall setup was too restrictive. Sorry for that... and thanks a lot for your great support.

**Comment by patrikhson** [comment]
Hey, I think I've found the thing you were looking for, just take a look here <http://sushykynte.danrhee.com/xygltjif>

Later, paf@frobbit.se

**Comment by patrikhson** [comment]
Hey,

I think this app is gonna be helpful for you, read more here <http://stendabumo.bobtransports.com/xyugw>

Best, paf@frobbit.se
