### ISSUE TITLE
s/.SE/IIS/

### ISSUE THREAD

**Issue by jschlyter** [dotse/zonemaster#412]
Zonemaster talks about .SE, but should really refer to IIS nowadays.

**Comment by sandoche2k** [comment]
Thanks for your comment. We will modify all instances of .SE to IIS.

**Comment by jschlyter** [comment]
Also there is a new logo, @pawal can help with that.

**Comment by pawal** [comment]
I think we are done. If there are more occurences of .SE, we will fix those when we find them.

**Comment by jschlyter** [comment]
FWIW, https://zonemaster.net/ still says .SE
