### ISSUE TITLE
Update the test specification for Address01

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#413]
Address01 lists all IP adresses that are special purpose blocks not to be used for a name server.

There is a better method for referencing those IP blocks that I discovered during my work with the TRTF draft.

IANA has two registries for those addresses, one for the IPv4 address space, and one for the IPv6 address space.

The IPv6 address space does not have an RFC outlining the IANA registry, but the function is implicitly described in RFC 1881. The IPv4 space registry was requested in RFC 7249.

In Address01 we should just reference these registries and remove the old tables:

 * http://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml
 * http://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml

We should probably also have code that automatically fetches this registry and converts it to the code we need for testing this.

A first question though, is our address tables complete? I haven't checked.

A not though: We must not use the complete table, only the special purpose blocks that are not global.

**Comment by sandoche2k** [comment]
@pawal - Change the test specification
@vlevigneron - Once the specification is finished ... look at implementing it...

**Comment by matsduf** [comment]
See #464.
