### ISSUE TITLE
address04 not implemented 

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster#415]
I do not find adress04 in lib/Zonemaster/Test/Address.pm, which tests bogon prefixes.

There is also  no test message for address04.md here : https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/TestMessages.md

**Comment by vlevigneron** [comment]
It has been implemented one year ago but removed afterwards.

https://github.com/dotse/zonemaster/issues/148

https://github.com/dotse/zonemaster/issues/162

If context has changed, it can be added again...


2015-10-06 15:05 GMT+02:00 sandoche2k <notifications@github.com>:

**Comment by sandoche2k** [comment]
@pawal  - Get copies of the feeds for IPv4 and IPv6 from Team Cymru
               - Add a requirement
               - Add a v4 test case for Bogon
@vlevigneron - Implement once all the above are done

**Comment by sandoche2k** [comment]
@pawal @vlevigneron @matsduf @mattias-p I went into the history of this issue. 

Address04 was implemented only for IPv6 and the specification was as follows:

``
1. Obtain the IPv6 addressses of the name servers from Method4 and Method5
2. Check if the addresses obtained in step1 is part of a bogon prefix by matching them with a bogon database
``
It was decided to remove the code, due to the following reasons:
``
1. We were depending on an external resource (Team Cymru) to check the bogon
2. If the external resource does not keep updating, then there is a possibility of false positive results
``
The solution proposed was to have an internal infrastructure which is populated from the external resource. 

It is not clear how well we can maintain an internal infrastructure. What i propose is that modify the existing specifications of Address04 as follows:

``
1. Obtain the IP addressses of the name servers from Method4 and Method5
2. Check if the addresses obtained in step1 is part of a bogon prefix by matching them with Team Cymru bogon database using DNS 
For example: 
``
dig +short IP4reverse.v4.fullbogons.cymru.com. 127.0.0.2
dig +short IP6reverse.v6.fullbogons.cymru.com. 127.0.0.2
``
If the result of the DNS request is ``127.0.0.2``, then it is a bogon.

Do any of you have an issue with the solution proposed.

**Comment by matsduf** [comment]
@sandoche2k , your commands are not valid:
```
dig +short IP4reverse.v4.fullbogons.cymru.com. 127.0.0.2
dig +short IP6reverse.v6.fullbogons.cymru.com. 127.0.0.2
```
Do you mean "@IP4reverse.v4.fullbogons.cymru.com"? But IP4reverse.v4.fullbogons.cymru.com is not a defined name.

**Comment by pawal** [comment]
See the text under Address Requirements in this draft: https://github.com/CENTRccTLDs/TRTF/blob/master/ietf/draft-wallstrom-dnsop-dns-delegation-requirements.md

**Comment by sandoche2k** [comment]
@matsduf "IPv4reverse", i meant is the reverse of the IPv4 address to test.

**Comment by matsduf** [comment]
The query should be, e.g.
```
dig +short 1.1.168.192.bogons.cymru.com A
```
and if the reply is "127.0.0.2" it means that 192.168.1.1 is part of a bogon prefix.

Is it OK to build in such a dependency to a commercial company?

**Comment by sandoche2k** [comment]
@pawal programming-wise ... Is it easy to test with the IANA registry "http://www.iana.org/assignments/ipv6-address-space/ipv6-address-space.xml". 

Will it impact the performance? Why do you think TeamCymru is not reliable?

**Comment by pawal** [comment]
Yes, compile in the IANA registries (IPv4 and IPv6) in the code (pre-build time, att your convenience). Performance will be better than Cymru lookups, since they are code lookups and not lookups through the network.

Cymru is reliable, but not something you do standards on, or reference implementation to that standard.

@matsduf - IIS is purchasing this service and have local feeds for the Zonemaster project, and they are non-profit. http://www.team-cymru.org/

**Comment by sandoche2k** [comment]
@pawal - Thanks

**Comment by matsduf** [comment]
Building in the IANA registry means that we have to update Zonemaster every time it changes. It is also a manual step, i.e. you cannot automatically extract the information from the databases as far as I can see. Updates do not seem to happen very often, however, so it might not be a problem.

I think that both compiling in the information and using Cymru are acceptable solutions. Using Cymru is simpler in the sense that they take care of any updates.

**Comment by pawal** [comment]
@matsduf You added this issue in June: https://github.com/dotse/zonemaster/issues/464

**Comment by sandoche2k** [comment]
@vlevigneron Based on the discussions, there is confirmation that we need address04 implemented for both IPv4 and IPv6. 

We have two solutions : 1. from Team cymru and 2. from IANA registry.  

@pawal suggests IANA registry wherein @matsduf suggests team cymru. Which of the two solutions will easy for you to implement and which one will better performance wise. Can you enlighten us @vlevigneron

**Comment by matsduf** [comment]
I am open for both solutions. 

It is quite clear how to use the Cymru solution.

The IANA solution requires fetching http://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.csv and extracting all records with status (next to last field) "ALLOCATED" or "LEGACY". For sanity check that field should only contains "ALLOCATED", "LEGACY" or "RESERVED". And fetching http://www.iana.org/assignments/ipv6-unicast-address-assignments/ipv6-unicast-address-assignments.csv and extracting all records with status (next to last field) "ALLOCATED". For sanity check that field should only contains ALLOCATED" or "RESERVED". 

If the IANA solution is used as above, we will get some addresses that are in fact "RESERVED". E.g. 2001:0000::/23 is defined as "ALLOCATED", but when you read the note in the last field is says that in fact parts of it are "RESERVED". By some manual work those issues could be solved, but that, again, requires maintenance.

Can we trust that Cymru has a correct implementation?

**Comment by pawal** [comment]
Cymru has several times given the user strange data.

**Comment by vlevigneron** [comment]
Well, I guess it is reasonnable and not that hard to implement the IANA solution. We should also provide an independent script that can be used to fetch on a regular basis the last versions of csv. I will work on that.

**Comment by sandoche2k** [comment]
Referred in #464
