### ISSUE TITLE
Allow requests through a resolver

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#417]
The last version of DNSviz has a new feature, which is very useful: perform the tests through a given resolver ("-s $RESOLVER"). This allows testing for cases when the resolver mangles the answers of the authoritative name server (see https://lists.dns-oarc.net/pipermail/dns-operations/2015-October/013790.html for a funny example).

**Comment by matsduf** [comment]
@bortzmeyer  Not within the Zonemaster scope.
