### ISSUE TITLE
ZoneMaster does not test RFC 4509 rules

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#418]
RFC 4509 says (sections 3 and 6.1) that DS records should be ignored if they are hashed with SHA-1 while a SHA-2-hashed DS exist. 

An example today is dollar.bank: 

```
1205 8 2 B5C2B6B547A6CD6626327E99CC1F52DD21BE7B067993B8AE235872DE 430A3819
2011 8 1 3DFF90267BFFFE92D188F1217317B2CD0B4FF8D2
```  

The first DS is hashed with SHA-256 and points to nothing. The second one points to an existing key but is ignored because of RFC 4509.

Most resolvers (Unbound, BIND, dnsmasq, Verisign Public DNS) abide by this rule and return SERVFAIL (an exception is Google Public DNS).

DNSviz flags this error. But no ZoneMaster 
https://zonemaster.net/test/38805

**Comment by pawal** [comment]
This needs clarifications on our test specifications as well.

**Comment by bortzmeyer** [comment]
A bug has been filed for Google Public DNS (#1162, private). Google claims it is indeed a bug and they will fix it.

**Comment by sandoche2k** [comment]
@pawal @bortzmeyer 

Modification in the test spec "https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/DNSSEC-TP/dnssec02.md"

```
1. Retrieve the DS RR set from the parent zone with digest type '2'
2.If digest type '2' exists, shortlist only those DS RR, else go to step 3
2a.If no Key Tag from the DS RR matches any Key Tag from the DNSKEY RR, this test case fails.
2b. Convert the DNSKEY RR set to DS records with the same algorithms as those from the parent zone.
2c. If none of the converted DNSKEY RR matches with any of the DS from the parent zone, this test case fails.
3. Retrieve the DNSKEY RR set from the child zone
3a.If no Key Tag from the DS RR matches any Key Tag from the DNSKEY RR, this test case fails.
3b.Convert the DNSKEY RR set to DS records with the same algorithms as those from the parent zone.
3c.If none of the converted DNSKEY RR matches with any of the DS from the parent zone, this test case fails.
```

**Comment by pawal** [comment]
@bortzmeyer Need advise on how to combine this with what is in #344. Should we completely ignore the DS with SHA-1 when there is SHA-256 for the same or different key?

Or should we possibly primarily test the SHA-256 DS chain, and only secondary test the chain with the SHA-1 DS with a validation failure resulting on a message with less severity?

**Comment by sandoche2k** [comment]
@bortzmeyer Need advise on how to combine this with what is in #344. Should we completely ignore the DS with SHA-1 when there is SHA-256 for the same or different key?

Or should we possibly primarily test the SHA-256 DS chain, and only secondary test the chain with the SHA-1 DS with a validation failure resulting on a message with less severity?
