### ISSUE TITLE
Better handling of IDN domain

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#421]
The Web interface, when an Unicode name is used (something which is reasonable on the Web) replies "Can't get syntax test result". The ideal would be to accept IDN names. At least the error message should be clearer.

**Comment by sandoche2k** [comment]
@bortzmeyer fixed https://zonemaster.net/test/cb9087ea0c489d46

**Comment by lanodan** [comment]
Looks like this issue should be reopened: https://zonemaster.net/result/2bcf067c8b043e29

**Comment by matsduf** [comment]
@lanodan, thank you for reporting this. A fix is planned within two weeks. See issue https://github.com/zonemaster/zonemaster-backend/issues/931
