### ISSUE TITLE
Exception in CPAN::Exception::yaml_process_error

### ISSUE THREAD

**Issue by patrikhson** [dotse/zonemaster#427]
When installing on Debian I get the following:

cpan[2]> reports IIS/Zonemaster-v1.0.7.tar.gz
Distribution: I/II/IIS/Zonemaster-v1.0.7.tar.gz
Fetching 'http://www.cpantesters.org/show/Zonemaster.yaml'...DONE

Catching error: "CPAN::Exception::yaml_process_error=HASH(0xf137008)" at /usr/share/perl/5.20/CPAN.pm line 392.
	CPAN::shell() called at /usr/share/perl/5.20/App/Cpan.pm line 339
	App::Cpan::_process_options("App::Cpan") called at /usr/share/perl/5.20/App/Cpan.pm line 422
	App::Cpan::run("App::Cpan") called at /usr/bin/cpan line 12

**Comment by pawal** [comment]
What happens if you just run cpan -i Zonemaster from your sh?

**Comment by patrikhson** [comment]
That worked, although I have no idea whether that worked because I forced an install earlier. I.e. I did not try a "clean install" this time.

The error I reported I got when I followed the installation instructions to the letter...

**Comment by sandoche2k** [comment]
@patrikhson  Clean install on debian 7.9 (Wheezy) did not show any errors.
