### ISSUE TITLE
CPAN::DistnameInfo missing from installation instructions

### ISSUE THREAD

**Issue by patrikhson** [dotse/zonemaster#428]
When installing on Debian, I found CPAN::DistnameInfo be missing:

cpan[3]> reports IIS/Zonemaster-v1.0.7.tar.gz

Distribution: I/II/IIS/Zonemaster-v1.0.7.tar.gz

CPAN::DistnameInfo not installed; cannot continue

**Comment by pawal** [comment]
I am not sure if this is a Zonemaster issue or something else. And this is since I get even more strange errors when replicating the issue.

While CPAN::DistnameInfo was not installed on my system I got the same error as you see, but installing it gives me this error:

```
cpan[3]> reports IIS/Zonemaster-v1.0.7.tar.gz
Distribution: I/II/IIS/Zonemaster-v1.0.7.tar.gz
Fetching 'http://www.cpantesters.org/show/Zonemaster.yaml'...DONE

Catching error: "CPAN::Exception::yaml_not_installed=HASH(0x7fe18682e348)" at /System/Library/Perl/5.18/CPAN.pm line 392, <FIN> line 1.
	CPAN::shell() called at /System/Library/Perl/5.18/App/Cpan.pm line 338
	App::Cpan::_process_options('App::Cpan') called at /System/Library/Perl/5.18/App/Cpan.pm line 421
	App::Cpan::run('App::Cpan') called at /usr/bin/cpan5.18 line 13
```

**Comment by sandoche2k** [comment]
@patrikhson with the current version - 1.0.10 of the engine, it seems the issue is solved. Can you confirm it?
