### ISSUE TITLE
What about greying (or other color) a disabled check ?

### ISSUE THREAD

**Issue by jpierre03** [dotse/zonemaster#430]
When an option is deselect some check are not performed.

By now, those checks description indicate "IPv6 is disabled, not ... ", "IPv4 is enabled, can send ..." and so on.

Disabled check and enabled checks are displayed with "alert-INFO" bootstrap class.
I know errors checks are displayed with "alert-CRITICAL".

What about creation of an "alert-DISABLED" bootstrap class to visualy identify disabled checks ?

Example of mixed checks (enabled and disabled) : #429 ,  https://zonemaster.net/test/8f743ea6eff57729

**Comment by sandoche2k** [comment]
@jpierre03 thanks for your input. we will discuss and if accepted will be part of the next release.

**Comment by matsduf** [comment]
Not a priority.
