### ISSUE TITLE
Bug in comparison between parent and child

### ISSUE THREAD

**Issue by einar** [dotse/zonemaster#439]
"https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Delegation-TP/delegation07.md". If one, or more, of the domains' name servers are "in-zone" then Zonemaster must also check if IP-adresses are consistent between parent and child. Today ZM simply checks if the names are consistent, this only works for out-of-zone name servers.

This was found checking "nordic-backup.com" where the parent pointed at 4 distinct IP-adresses and the child at 2 identical to the parent but also 2 different ones; although the same FQDNs were used. Check history on "zonemaster.net" for the domain if unclear. ;) :p

**Comment by sandoche2k** [comment]
@einar IP address consistency is tested by https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Consistency-TP/consistency05.md
