### ISSUE TITLE
ASN test should only look at authoritative nameservers at the child

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#441]
Looking at the domain swedbank.se, it has a superfluous name server listed at the parent. This name is included in the test for ASN used for the domain. It should not. DNSCheck has this done right.

**Comment by sandoche2k** [comment]
Hence, in this case: 

Modify "https://github.com/dotse/zonemaster/blob/a6e0724a2aadaca2bbad29c1e4299544daa10f18/docs/specifications/tests/Connectivity-TP/connectivity03.md"

From
```
Obtain the IP addresses of the name servers from Method4 and Method5.
```
To
```
Obtain the IP addresses of the name servers from Method5.
```

**Comment by pawal** [comment]
@sandoche2k yes, could you do this as a pull request?

**Comment by sandoche2k** [comment]
@vlevigneron Modifications have been made to "connectivity03.md". Pls implement accordingly.
