### ISSUE TITLE
basic01 to find parent is a little bit fishy...

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#447]
The purpose of basic01 is to find out if there is a parent for the zone. _basic02_ is to find out if there is data in the parent for the zone to be tested.

```
$> zonemaster-cli --test Basic/basic01 aldkjsdasd.se
Seconds Level     Message
======= ========= =======
   1.02 CRITICAL  Nameserver for zone se responded with NXDOMAIN to query for glue.
```

So the above result does not makes sense. However, the same test for a domain that exists:

```
$>zonemaster-cli --test Basic/basic01 apa.se
Seconds Level     Message
======= ========= =======
Looks OK.
```

**Comment by sandoche2k** [comment]
@pawal - Hence, we need to modify the error response for basic 01? such as .. 

"No authoritative servers found for this domain" ?

**Comment by pawal** [comment]
If the purpose of basic01 is to find out that there is a parent zone for the domain, obviously both statements are false. Since the domain se exists in the example above, the answer should rather state something about that the parent domain exists, rather than saying that the zone we want to test does not exist. The test case is labeled "The domain must have a parent domain":
https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Basic-TP/basic01.md

**Comment by sandoche2k** [comment]
The test case is labeled "The domain must have a parent domain":

If the domain itself does not exist, how could we say that its parent exists.

**Comment by pawal** [comment]
Because it has a parent, in this case the .se-domain.

Or do you say that a child can exist without a parent? ;)

**Comment by sandoche2k** [comment]
For a decision .. so that @vlevigneron could modify accordingly ..  what is your suggestion for the "error message"?

$> zonemaster-cli --test Basic/basic01 aldkjsdasd.se
Seconds Level     Message
======= ========= =======
   1.02 CRITICAL  Nameserver for zone se responded with NXDOMAIN to query for glue.

(My sueggestion)
**==> "Nameserver for zone se responded with NXDOMAIN" **

And for 

$>zonemaster-cli --test Basic/basic01 apa.se
Seconds Level     Message
======= ========= =======
Looks OK.

(My sueggestion)
**==> "Nameserver for zone se has an authoritative response" **

**Comment by pawal** [comment]
I do not think the log message is the right thing to consider here, bur rather the test case itself.

In order to explain, I am writing code to test if a domain exists or not. Rather then re-invent the wheel, I decided to try Zonemaster to do it for me. Since basic01 was the perfect code for this (I thought) I was surprised to find this message for a non-existent zone. For me, the expected output would have been a log message telling me what the parent domain was.

Reading the objective of basic01, it is clear that the title has little to do with the objective:

> In order for a domain to work, it must be delegated to from a domain higher up in the DNS hierarchy
> (a parent domain). However, note that this requirement does not concern the root domain.

Perhaps a better title is "The domain must be delegated from its parent domain".

**Comment by sandoche2k** [comment]
I do accept that "The domain must be delegated from its parent domain" seems better than "The domain must have a parent domain".

But, i think we have moved away from the objective of the Issue. Your initial view was that the results does not make sense and i also do agree on it :-). 

Maybe a better way to put it is : 

$> zonemaster-cli --test Basic/basic01 aldkjsdasd.se
Seconds Level     Message
======= ========= =======
   1.02 CRITICAL  Nameserver for zone se responded with NXDOMAIN to query for glue.

(My suggestion)
**==> "Nameserver for the parent zone se responded with NXDOMAIN" **

Either we will keep the logs as it is (or) accept the one i suggested above (or) re phrase. 

Once this is done we can update accordingly and close the issue.

**Comment by matsduf** [comment]
An analysis of the specification BASIC01, and any updates, before updating the code.

**Comment by patrikhson** [comment]
Hi,

I have some brilliant ideas regarding the issues we've discussed last time, please read 'em here <http://thapyxyki.georgefinancialservices.com/xyggp>

Speak to you later, paf@frobbit.se

**Comment by sandoche2k** [comment]
Move to 2017.1, since specification is not yet complete.

**Comment by vlevigneron** [comment]
@matsduf @sandoche2k Are the specifications completed yet ?

**Comment by pawal** [comment]
Is this really fixed? Where is the code commit?

**Comment by matsduf** [comment]
Fixed by https://github.com/dotse/zonemaster-engine/pull/284
