### ISSUE TITLE
basic02 reports nothing if the domain has no name servers delegated

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#448]
The test basic02 should at least report something when there are no name servers provided in the delegation.

**Comment by sandoche2k** [comment]
@pawal For clarification : This test does fails .. for example 

zonemaster-cli --test Basic/basic02 motounit.nl
Seconds Level     Message
======= ========= =======
  12.63 NOTICE    Nameserver ns364992.ovh.net/37.59.32.10 did not respond to NS query.
  12.64 ERROR     Nameserver sdns2.ovh.net/2001:41d0:1:4a8d::1 did not return NS records. RCODE was REFUSED.
  12.65 ERROR     Nameserver sdns2.ovh.net/213.251.188.141 did not return NS records. RCODE was REFUSED.

**Comment by pawal** [comment]
Yes, this is as designed. The parent has name servers in the delegation, but the child does not have any authoritative working name servers, since those are servfailing.

**Comment by matsduf** [comment]
It is not clear what the error is. Close and reopen if the error is found.
