### ISSUE TITLE
Translation issue 

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster#449]
In French the result in the Zone category for the test (https://zonemaster.fr/test/7892f853ec0ea69a) is 

"Aucune cible (MX=mx2.grenoble.cnrs.fr/MX=mx1.grenoble.cnrs.fr) n'a été trouvée pour faire parvenir un message à ce nom de domaine."

In english the result in the Zone category for the same test is "Target (MX=mx2.grenoble.cnrs.fr/MX=mx1.grenoble.cnrs.fr) found to deliver e-mail for the domain name."

**Comment by vlevigneron** [comment]
Yes, I got it. I'll fix it.

le 02 févr., sandoche2k a ?crit :
> In French the result in the Zone category for the test (https://zonemaster.fr/test/7892f853ec0ea69a) is 
> 
> "Aucune cible (MX=mx2.grenoble.cnrs.fr/MX=mx1.grenoble.cnrs.fr) n'a été trouvée pour faire parvenir un message à ce nom de domaine."
> 
> In english the result in the Zone category for the same test is "Target (MX=mx2.grenoble.cnrs.fr/MX=mx1.grenoble.cnrs.fr) found to deliver e-mail for the domain name."
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster/issues/449

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr

**Comment by vlevigneron** [comment]
Already fixed in dotse/zonemaster-engine#144
