### ISSUE TITLE
Would be nice to add a count of name servers

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#453]
When testing domains with long delegations (such as [fox.com](https://zonemaster.net/test/0ee4fe4e0cd08d73)), it would be nice to have a tally of the name servers. 

For instance, instead of:

> Parent and child list enough nameservers (asia2.akam.net; eur1.akam.net; eur3.akam.net; ns1-40.akam.net; ns1-75.akam.net; use2.akam.net; usw1.akam.net; usw7.akam.net). Lower limit set to 2. 

Use:

> Parent and child list enough nameservers (**8 nameservers**, asia2.akam.net; eur1.akam.net; eur3.akam.net; ns1-40.akam.net; ns1-75.akam.net; use2.akam.net; usw1.akam.net; usw7.akam.net). Lower limit set to 2.

**Comment by pawal** [comment]
That would be a very good enhancement, yes.

**Comment by sandoche2k** [comment]
+1
