### ISSUE TITLE
Can't call method "rcode" on an undefined value at

### ISSUE THREAD

**Issue by tobbe-eklov** [dotse/zonemaster#463]
Installed/upgrades Zonemaster-cli from cpan yesterday at a Ubuntu 16.04

bollebygd.se:  22.75 CRITICAL  SYSTEM:MODULE_ERROR module=Zonemaster::Test::Address; msg=Can't call method "rcode" on an undefined value at /usr/local/share/perl/5.22.1/Zonemaster/Test/Address.pm line 165, <DATA> line 20.

kil.se forshaga.se have same issue.

/Tobbe

**Comment by matsduf** [comment]
All three (bollebygd.se, kil.se and forshaga.se) have nameservers with IP addresses, the reverse of which go through a CNAME. It is, however, not possible to resolve that name. In the first case the zone is not defined in the server, in the other two cases the servers do not respond at all.

From the code

   158              # In case of Classless IN-ADDR.ARPA delegation, query returns
   159              # CNAME records. A PTR query is done on the CNAME.
   160              if ( $p->rcode eq q{NOERROR} and $p->get_records( q{CNAME}, q{answer} ) ) {
   161                  my ( $cname ) = $p->get_records( q{CNAME}, q{answer} );
   162                  $p = Zonemaster::Recursor->recurse( $cname->cname, q{PTR} );
   163              }
   164  
   165              if ( $p->rcode ne q{NOERROR} or not $p->get_records( q{PTR}, q{answer} ) ) {
   166                  push @results,

It looks like some error checking is needed between line 162 and 165.

**Comment by pawal** [comment]
When will this be released? It causes serious problems while testing the TLDs ci and bf.
