### ISSUE TITLE
Document new procedure for version of specifications and versioning of them

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster#465]

**Comment by sandoche2k** [comment]
Relates to https://github.com/dotse/zonemaster-backend/issues/217

**Comment by sandoche2k** [comment]
@matsduf do you think this issue should be part of 2016.2?

**Comment by matsduf** [comment]
No, we should move it. It should be completed long time before the release in which we should implement it.

**Comment by sandoche2k** [comment]
Changes to specifications will be merged to a separate branch, until implementation is completed.
