### ISSUE TITLE
Don't mark missing DNSSEC entries with a green check

### ISSUE THREAD

**Issue by GieltjE** [dotse/zonemaster#467]
When a domain is missing both DS and DNSKEY records it would be better to mark the domain with a red cross. If it is missing DS records it should be marked with an orange tick as this is a valid situation but not recommended for the long run (it effectivly disables DNSSEC for the end users).

The current practice of marking domains without DNSSEC green (with the text "There are neither DS nor DNSKEY records for the zone." under the + button) neither gives the correct impression nor does it promote a better internet.

**Comment by sandoche2k** [comment]
I am referring to https://github.com/dotse/zonemaster-gui/issues/154 and closing this issue.
