### ISSUE TITLE
Create specification of undelegated test

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster#495]
Create a detailed specification of how an undelegated specification should be performed. When that is done, the issue in https://github.com/dotse/zonemaster-engine/issues/238 can be resolved.

**Comment by sandoche2k** [comment]
@sandoche2K https://github.com/dotse/zonemaster/pull/504 verify and start implementation @vlevigneron

**Comment by sandoche2k** [comment]
Implementation to be done by @vlevigneron

**Comment by matsduf** [comment]
Fixed by PR #526
