### ISSUE TITLE
Review version schema

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster#506]
https://github.com/dotse/zonemaster/blob/master/docs/design/Versions%20and%20Releases.md

https://github.com/dotse/zonemaster/blob/master/docs/internal-documentation/maintenance/ReleasePlan.md

https://github.com/dotse/zonemaster/wiki/Zonemaster-Distribution-Releases

**Comment by matsduf** [comment]
PR #510 created.

**Comment by sandoche2k** [comment]
Closed by PR #510
