### ISSUE TITLE
The ReleaseProcess document needs updates

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster#511]
The https://github.com/dotse/zonemaster/blob/master/docs/internal-documentation/maintenance/ReleaseProcess.md document needs updates:

* Zonemaster-LDNS needs to be included in the document.
* In section 7 there are examples of Perl versions. There should be a reference to where a list of supported versions can be found.
* Other updates..

**Comment by sandoche2k** [comment]
Updates have been done as part of release 2017.3
