### ISSUE TITLE
Markdown rendering

### ISSUE THREAD

**Issue by mattias-p** [dotse/zonemaster#513]
[Github has updated its markdown rendering engine](https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown), breaking some of documents. We need to update our markup to make it compliant with the new spec.

Specifically I've noted problems with headings that don't render properly anymore. [The new spec](https://github.github.com/gfm/#atx-headings) doesn't recognize NBSP as a separator between the '#' prefix and the heading text. We need to replace our NBSP characters with SPACE characters.

**Comment by mattias-p** [comment]
Merged into develop.

**Comment by mattias-p** [comment]
I made a review and found a bunch of other rendering problems, presumably (but not necessarily) introduced by the update to the markdown renderer.

Broken general layout:
* docs/internal-documentation/distrib-testing/Debian-Testing-Instructions.md

Broken tables:
* docs/requirements/TestRequirements.md#tests-to-implement
* docs/internal-documentation/functional-tests/Configuration-TP/configuration04.md#appendix

Broken image links:
* docs/design/README.md
* docs/internal-documentation/requirements/README.md
* docs/requirements/README.md

**Comment by sandoche2k** [comment]
I think we can remove this directory docs/internal-documentation/distrib-testing. As, we are using the general installation instructions for preparing the release, this can be removed. I will make a PR, if you agree.

**Comment by matsduf** [comment]
The installation document does not cover the general set-up of a server before installation, e.g. added locals. I think the documents could be useful, but they need updates.

**Comment by sandoche2k** [comment]
Agreed. But "Debian-Testing-Instructions.md" should be removed.

**Comment by matsduf** [comment]
@sandoche2k, do you want to keep the directory with "Debian-Preparation.md" and "FreeBSD-Preparation.md" or do you want to move it somewhere else?

I think it is fine to remove "Debian-Testing-Instructions.md".

**Comment by mattias-p** [comment]
@matsduf This PR is about getting rid of broken markup. If we also want to rearrange the repository I suggest a separate issue is created for that.
