### ISSUE TITLE
Test that the apex DNSKEY RRset is signed with each algorithms of the DS for the zone 

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#527]
RFC 4035, section 2.2 "There MUST be an RRSIG
for each RRset using at least one DNSKEY of EACH ALGORITHM [my emphasis] in the zone apex DNSKEY RRset.  The apex DNSKEY RRset itself
MUST be signed by each algorithm appearing in the DS RRset located at
the delegating parent (if any)."

Currently, Zonemaster does not check that (unlike DNSviz, see for instance http://dnsviz.net/d/museum/WgzFPw/dnssec/)

As of today, no resolver I know SERVFAILs on this violation of the RFC. Still, it would be better to warn the zone owner.

**Comment by matsduf** [comment]
@bortzmeyer, good suggestions. As I understand your suggestion it is limited to that the DNSKEY RRset in apex is signed with all algorithms. Your quote says "each RRset". I'd like to edit the headline to make it more clear.

**Comment by matsduf** [comment]
@bortzmeyer, RFC 6840 updates RFC 4035. Created two new issues instead: #528 and #529.

**Comment by pawal** [comment]
This was also a duplicate of #231.

**Comment by bortzmeyer** [comment]
OK, I agree with two new issues  #528 and #529.

**Comment by matsduf** [comment]
@bortzmeyer, thank you for reviewing.
