### ISSUE TITLE
The smallest possible legal referral packet is larger than 512 octets

### ISSUE THREAD

**Issue by oryagel** [dotse/zonemaster#536]
Hi.
I'm not sure that this is the place for that question, so please let me know if not.
I scanned my domain with zonemaster.net. The result of the scan return the following error:
`The smallest possible legal referral packet is larger than 512 octets (it is 536)`
I tried to look that up but didn't find a good explanation about the issue and how to fix that.
What should I do to fix that error?

Thanks

**Comment by matsduf** [comment]
@oryagel, I think you just got an information message. Was it really an error message? Can you rerun the test and add the link to the test to this issue?

**Comment by matsduf** [comment]
Yes, it is a WARNING. It says that the delegation of tccsetup.com from .COM requires a package size larger than 512. I have to investigate to see if the message is really correct. 

Your delegation does have many nameserver names, and the names do not share the domain part, which makes compression impossible. So this means that the size of the delegation will be large. To fit all the IP addresses the response will be larger than 512 bytes, which all delegations should be limited to.

I hope this explains.

**Comment by oryagel** [comment]
Thanks @matsduf 
Do you know what the actual impact of that? How can I resolve that?

**Comment by matsduf** [comment]
@oryagel, as I said, I have to investigate to see if the warning is correct. If the delegation is larger than 512 bytes, DNS resolvers without support for EDNS need to switch to TCP, which requires more time for resolution.

Today you have the following delegation of tccsetup.com:

```
tccsetup.com.		NS	ns1.p17.dynect.net.
tccsetup.com.		NS	ns3.p17.dynect.net.
tccsetup.com.		NS	ns2.p17.dynect.net.
tccsetup.com.		NS	ns4.p17.dynect.net.
tccsetup.com.		NS	ns-420.awsdns-52.com.
tccsetup.com.		NS	ns-859.awsdns-43.net.
tccsetup.com.		NS	ns-1150.awsdns-15.org.
tccsetup.com.		NS	ns-1844.awsdns-38.co.uk.
```

If you want to reduce the delegation size you could remove some of the NS records. In practice you would not loose much redundancy.

```
tccsetup.com.		NS	ns1.p17.dynect.net.
tccsetup.com.		NS	ns2.p17.dynect.net.
tccsetup.com.		NS	ns-420.awsdns-52.com.
tccsetup.com.		NS	ns-859.awsdns-43.net.
```

**Comment by matsduf** [comment]
Created issue https://github.com/dotse/zonemaster-engine/issues/353
