### ISSUE TITLE
Missing Resolver TP

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster#592]
In the [Master Test Plan] there is a reference (link) to a non-existing [Resolver Test Plan].

@pawal, can you shed some light on the missing Test Plan? You seem to be the last person who updated the relevant part of [Master Test Plan].

What is the idea of a Resolver Test Plan? Is that really relevant for a tool testing the delegation of a domain name?

[Master Test Plan]: https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/MasterTestPlan.md
[Resolver Test Plan]: https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Resolver-TP/level.md

**Comment by pawal** [comment]
You might want to look at the git history to see if there was ever a resolver test plan. I forgot what it was about.

**Comment by matsduf** [comment]
It is not found in Git history. It does not fit into the framework. It should just be removed from the Master Test Plan.

**Comment by matsduf** [comment]
Solved by #593 (removing from Master Test Plan).
