### ISSUE TITLE
Consistency of IP address in Delegation to be Added 

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster#99]
There is a confusion on what was decided with respect to the title point during the meeting. 

Maybe someone who remember can please explain.

**Comment by kgaughan** [comment]
I think here's an example of the kind of issue this is meant to check for:

https://gist.github.com/kgaughan/4ab0f0fca88838cfa280

**Comment by matsduf** [comment]
This is already part of Consistency05.
