### ISSUE TITLE
Add SPF and possibly other mail related test cases [Feature Request]

### ISSUE THREAD

**Issue by Ressy66** [dotse/zonemaster#995]
Add, into, perhaps ZONE (or a new MX section) a test for SPF (using the SPF RR  as well as the TXT RR) - including if it is formatted correctly according to RFC 7208 (which replaced 4408)

If after consideration this is accepted as a to-do :

Recommended results:  
if RR  not exist, return as Warning.
if RR exists, then formatting test determines, if its ok return INFO or a failure return ERROR, considering -
-if policy is !all return ERROR   (useless might as well not have the record)
-if policy is ~all return NOTICE (soft fail, a notice so they are aware it wont block)

What you think ?

**Comment by matsduf** [comment]
Is an SPF test a DNS test or an email test? If Zonemaster is extended with SPF tests, should it also test for DKIM and DANE?

**Comment by Ressy66** [comment]
SPF test is a DNS test - yes its used in mail, but it works from data in DNS, It could be likened to MX RR

for example, RFC's say all the lookups it does can not exceed 10, else it will discard the rest and then yes mail would rejected by those honouring SPF on mail servers.

This came up yesterday on a local mailing list,  someones domain spf RR was pointing to external parties, causing delivery issues

 their own entries were IP's so so thats a  ZERO count, but they included three other domains spf records uing of include:  theres THREE, of those three,two of them had other includes and one of them about six or so, causing total lookups TWELVE, so last two were discarded, correctly as per RFC's, and obviously  they were sending out mail  from those two discardeds resulting in mail rejections.

So, I consider this a DNS related issue.

As for others, not sure if thats sarcasm or not :)  but were are not checking full SPF/TXT tests because that would mean the tester would need to enter their IP to see if mail passes, we are just checking for valid data.

DKIM, I use, but not a big supporter or "carer" about, like most admins in this part of the world because it fails on 99% of mailing lists, sure its handy for banks or e-commerce, but useless for average joe sending emails between each other, testing DKIM would mean validating signature great if you want to do it, but if checking it exists and is correctly formatted without testing signature, sarcasm or not, it would be a good call :)
